## Data Analytics

### Chapter 5: Data Modification 

Modifying data is a fundamental aspect of data analytics, allowing analysts to clean, transform, and prepare datasets for analysis. This chapter covers various techniques for modifying data effectively.

- **Rename**: Rename columns or indexes in a dataset to make them more descriptive or consistent with naming conventions. This is often done to improve readability and understanding of the data.

- **Set or Reset Index**: Change the index of a dataset to a different column or reset it to the default integer index. This can be useful for reordering data or preparing it for analysis.

- **Insert, Delete, and Update Values**: Modify the contents of a dataset by adding new rows, removing existing ones, or updating specific values. This is crucial for maintaining accurate and relevant data.

#### Generate Synthetic Data

In [2]:
import numpy as np
import pandas as pd

# Reproducible randomness
np.random.seed(42)

In [3]:
names = [
    "James", "Chris", "Adam", "Marian", "Peter",
    "Kevin", "Linda", "Emma", "Sophia", "Daniel",
    "Noah", "Olivia", "Lucas", "Grace", "Henry",
    "Liam", "Ava", "Mia", "Nathan", "Chloe"
]

majors = ["AI", "IT", "CSC", "SW"]

n = 20

df = pd.DataFrame({
    "Name": np.array(names),
    "Age": np.random.randint(18, 21, n),
    "Major": np.random.choice(majors, n),
    "GPA": np.round(np.random.uniform(2.0, 4.0, n), 2)
})

df

      Name  Age Major   GPA
0    James   20    SW  2.91
1    Chris   18    SW  3.57
2     Adam   20    AI  2.40
3   Marian   20    AI  3.03
4    Peter   18    SW  3.18
5    Kevin   18    IT  2.09
6    Linda   20    IT  3.22
7     Emma   19    AI  2.34
8   Sophia   20    SW  2.13
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
11  Olivia   20   CSC  3.62
12   Lucas   18   CSC  2.61
13   Grace   20   CSC  2.20
14   Henry   19    IT  3.37
15    Liam   18    SW  2.88
16     Ava   19    SW  2.24
17     Mia   19    SW  2.99
18  Nathan   19    SW  2.07
19   Chloe   19   CSC  3.82

#### 5.1. Retrieving Columns

You can retrieve specific columns from a dataset using indexing or the `loc` and `iloc` methods. This allows you to focus on the relevant data for your analysis.

In [4]:
print(df.columns)  # returns an Index object containing all column names
print(df.columns.to_list()) # converts the Index object into a regular Python list

Index(['Name', 'Age', 'Major', 'GPA'], dtype='object')
['Name', 'Age', 'Major', 'GPA']

#### 5.2. Renaming Existing Columns

Renaming columns is a common task in data manipulation, especially when working with datasets that have unclear or inconsistent column names. You can use the `rename()` method to rename columns in a DataFrame.

In [5]:
# The recommended way to rename columns is with df.rename()
df_rename = df.copy()
df_rename = df_rename.rename(columns={"GPA": "Grade"})

df_rename

      Name  Age Major  Grade
0    James   20    SW   2.91
1    Chris   18    SW   3.57
2     Adam   20    AI   2.40
3   Marian   20    AI   3.03
4    Peter   18    SW   3.18
5    Kevin   18    IT   2.09
6    Linda   20    IT   3.22
7     Emma   19    AI   2.34
8   Sophia   20    SW   2.13
9   Daniel   20    AI   3.90
10    Noah   20    AI   3.93
11  Olivia   20   CSC   3.62
12   Lucas   18   CSC   2.61
13   Grace   20   CSC   2.20
14   Henry   19    IT   3.37
15    Liam   18    SW   2.88
16     Ava   19    SW   2.24
17     Mia   19    SW   2.99
18  Nathan   19    SW   2.07
19   Chloe   19   CSC   3.82

In [6]:
# Rename multiple columns simultaneously.
df_rename = df_rename.rename(columns={
    "Name": "Student",
    "Major": "Program",
    "GPA": "Grade"
})

df_rename

   Student  Age Program  Grade
0    James   20      SW   2.91
1    Chris   18      SW   3.57
2     Adam   20      AI   2.40
3   Marian   20      AI   3.03
4    Peter   18      SW   3.18
5    Kevin   18      IT   2.09
6    Linda   20      IT   3.22
7     Emma   19      AI   2.34
8   Sophia   20      SW   2.13
9   Daniel   20      AI   3.90
10    Noah   20      AI   3.93
11  Olivia   20     CSC   3.62
12   Lucas   18     CSC   2.61
13   Grace   20     CSC   2.20
14   Henry   19      IT   3.37
15    Liam   18      SW   2.88
16     Ava   19      SW   2.24
17     Mia   19      SW   2.99
18  Nathan   19      SW   2.07
19   Chloe   19     CSC   3.82

In [7]:
# You can also replace all column names directly.
df_rename = df.copy()
df_rename.columns = ["Student", "Age", "Program", "Grade"]
df_rename

   Student  Age Program  Grade
0    James   20      SW   2.91
1    Chris   18      SW   3.57
2     Adam   20      AI   2.40
3   Marian   20      AI   3.03
4    Peter   18      SW   3.18
5    Kevin   18      IT   2.09
6    Linda   20      IT   3.22
7     Emma   19      AI   2.34
8   Sophia   20      SW   2.13
9   Daniel   20      AI   3.90
10    Noah   20      AI   3.93
11  Olivia   20     CSC   3.62
12   Lucas   18     CSC   2.61
13   Grace   20     CSC   2.20
14   Henry   19      IT   3.37
15    Liam   18      SW   2.88
16     Ava   19      SW   2.24
17     Mia   19      SW   2.99
18  Nathan   19      SW   2.07
19   Chloe   19     CSC   3.82

#### 5.3. Setting an Existing Column as the Index

To set an index, you can use the `set_index()` method. This allows you to designate a specific column as the index of the DataFrame, which can be useful for data organization and retrieval.

In [8]:
df_rename = df.copy()
df_rename = df_rename.set_index("Name")

df_rename

        Age Major   GPA
Name
James    20    SW  2.91
Chris    18    SW  3.57
Adam     20    AI  2.40
Marian   20    AI  3.03
Peter    18    SW  3.18
Kevin    18    IT  2.09
Linda    20    IT  3.22
Emma     19    AI  2.34
Sophia   20    SW  2.13
Daniel   20    AI  3.90
Noah     20    AI  3.93
Olivia   20   CSC  3.62
Lucas    18   CSC  2.61
Grace    20   CSC  2.20
Henry    19    IT  3.37
Liam     18    SW  2.88
Ava      19    SW  2.24
Mia      19    SW  2.99
Nathan   19    SW  2.07
Chloe    19   CSC  3.82

#### 5.4. Restoring the Default Index

When restoring the default index of a DataFrame, you can use the `reset_index()` method. This is useful when you want to revert to the original integer-based index after setting a different column as the index.

In [9]:
df_rename = df_rename.reset_index()
df_rename

      Name  Age Major   GPA
0    James   20    SW  2.91
1    Chris   18    SW  3.57
2     Adam   20    AI  2.40
3   Marian   20    AI  3.03
4    Peter   18    SW  3.18
5    Kevin   18    IT  2.09
6    Linda   20    IT  3.22
7     Emma   19    AI  2.34
8   Sophia   20    SW  2.13
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
11  Olivia   20   CSC  3.62
12   Lucas   18   CSC  2.61
13   Grace   20   CSC  2.20
14   Henry   19    IT  3.37
15    Liam   18    SW  2.88
16     Ava   19    SW  2.24
17     Mia   19    SW  2.99
18  Nathan   19    SW  2.07
19   Chloe   19   CSC  3.82

#### 5.5. Inserting New Columns

Inserting a new column into a DataFrame can be done by assigning a new value to a column name that does not yet exist. This allows you to add additional data or features to your dataset for analysis.

In [10]:
df_new = df.copy()
df_new["Scholarship"] = False

df_new

      Name  Age Major   GPA  Scholarship
0    James   20    SW  2.91        False
1    Chris   18    SW  3.57        False
2     Adam   20    AI  2.40        False
3   Marian   20    AI  3.03        False
4    Peter   18    SW  3.18        False
5    Kevin   18    IT  2.09        False
6    Linda   20    IT  3.22        False
7     Emma   19    AI  2.34        False
8   Sophia   20    SW  2.13        False
9   Daniel   20    AI  3.90        False
10    Noah   20    AI  3.93        False
11  Olivia   20   CSC  3.62        False
12   Lucas   18   CSC  2.61        False
13   Grace   20   CSC  2.20        False
14   Henry   19    IT  3.37        False
15    Liam   18    SW  2.88        False
16     Ava   19    SW  2.24        False
17     Mia   19    SW  2.99        False
18  Nathan   19    SW  2.07        False
19   Chloe   19   CSC  3.82        False

In [11]:
df_new["Year"] = [1, 2, 3, 4] * 5
df_new

      Name  Age Major   GPA  Scholarship  Year
0    James   20    SW  2.91        False     1
1    Chris   18    SW  3.57        False     2
2     Adam   20    AI  2.40        False     3
3   Marian   20    AI  3.03        False     4
4    Peter   18    SW  3.18        False     1
5    Kevin   18    IT  2.09        False     2
6    Linda   20    IT  3.22        False     3
7     Emma   19    AI  2.34        False     4
8   Sophia   20    SW  2.13        False     1
9   Daniel   20    AI  3.90        False     2
10    Noah   20    AI  3.93        False     3
11  Olivia   20   CSC  3.62        False     4
12   Lucas   18   CSC  2.61        False     1
13   Grace   20   CSC  2.20        False     2
14   Henry   19    IT  3.37        False     3
15    Liam   18    SW  2.88        False     4
16     Ava   19    SW  2.24        False     1
17     Mia   19    SW  2.99        False     2
18  Nathan   19    SW  2.07        False     3
19   Chloe   19   CSC  3.82        False     4

#### 5.6. Inserting New Rows

Inserting new rows into a DataFrame can be accomplished using the `loc` method. This allows you to add new observations or records to your dataset, which can be useful for expanding your analysis or incorporating new data points.

Note that when using `loc`, make sure the list of values you provide matches the number of columns in the DataFrame to avoid errors.

In [12]:
df_new.loc[len(df_new)] = ["Alice", 19, "AI", 3.85, False, 3]
df_new.tail(5)

      Name  Age Major   GPA  Scholarship  Year
16     Ava   19    SW  2.24        False     1
17     Mia   19    SW  2.99        False     2
18  Nathan   19    SW  2.07        False     3
19   Chloe   19   CSC  3.82        False     4
20   Alice   19    AI  3.85        False     3

#### 5.7. Deleting Columns

Delete columns from a DataFrame using the `drop()` method. This is useful for removing irrelevant or redundant data, helping to streamline your dataset for analysis.

In [13]:
# To remove one or more columns, use drop().
df_drop = df_new.drop(columns=["Major"])
df_drop

      Name  Age   GPA  Scholarship  Year
0    James   20  2.91        False     1
1    Chris   18  3.57        False     2
2     Adam   20  2.40        False     3
3   Marian   20  3.03        False     4
4    Peter   18  3.18        False     1
5    Kevin   18  2.09        False     2
6    Linda   20  3.22        False     3
7     Emma   19  2.34        False     4
8   Sophia   20  2.13        False     1
9   Daniel   20  3.90        False     2
10    Noah   20  3.93        False     3
11  Olivia   20  3.62        False     4
12   Lucas   18  2.61        False     1
13   Grace   20  2.20        False     2
14   Henry   19  3.37        False     3
15    Liam   18  2.88        False     4
16     Ava   19  2.24        False     1
17     Mia   19  2.99        False     2
18  Nathan   19  2.07        False     3
19   Chloe   19  3.82        False     4
20   Alice   19  3.85        False     3

In [14]:
# To delete multiple columns
df_drop = df_new.drop(columns=["Age", "Major", "Scholarship"])
df_drop

      Name   GPA  Year
0    James  2.91     1
1    Chris  3.57     2
2     Adam  2.40     3
3   Marian  3.03     4
4    Peter  3.18     1
5    Kevin  2.09     2
6    Linda  3.22     3
7     Emma  2.34     4
8   Sophia  2.13     1
9   Daniel  3.90     2
10    Noah  3.93     3
11  Olivia  3.62     4
12   Lucas  2.61     1
13   Grace  2.20     2
14   Henry  3.37     3
15    Liam  2.88     4
16     Ava  2.24     1
17     Mia  2.99     2
18  Nathan  2.07     3
19   Chloe  3.82     4
20   Alice  3.85     3

In [15]:
# Removing a Column with pop()
major = df_new.pop("Major")
major

0      SW
1      SW
2      AI
3      AI
4      SW
5      IT
6      IT
7      AI
8      SW
9      AI
10     AI
11    CSC
12    CSC
13    CSC
14     IT
15     SW
16     SW
17     SW
18     SW
19    CSC
20     AI
Name: Major, dtype: object

#### 5.8. Deleting Rows

Deleting rows from a DataFrame can be done using the `drop()` method with the appropriate index labels. This is useful for removing specific observations that may be outliers or irrelevant to your analysis.

In [16]:
# Rows are removed by specifying their index labels.
df_drop_index = df_new.drop(index=0)
df_drop_index

      Name  Age   GPA  Scholarship  Year
1    Chris   18  3.57        False     2
2     Adam   20  2.40        False     3
3   Marian   20  3.03        False     4
4    Peter   18  3.18        False     1
5    Kevin   18  2.09        False     2
6    Linda   20  3.22        False     3
7     Emma   19  2.34        False     4
8   Sophia   20  2.13        False     1
9   Daniel   20  3.90        False     2
10    Noah   20  3.93        False     3
11  Olivia   20  3.62        False     4
12   Lucas   18  2.61        False     1
13   Grace   20  2.20        False     2
14   Henry   19  3.37        False     3
15    Liam   18  2.88        False     4
16     Ava   19  2.24        False     1
17     Mia   19  2.99        False     2
18  Nathan   19  2.07        False     3
19   Chloe   19  3.82        False     4
20   Alice   19  3.85        False     3

In [17]:
# Delete multiple rows.
df_drop_index = df_new.drop(index=[0, 3, 5])
df_drop_index

      Name  Age   GPA  Scholarship  Year
1    Chris   18  3.57        False     2
2     Adam   20  2.40        False     3
4    Peter   18  3.18        False     1
6    Linda   20  3.22        False     3
7     Emma   19  2.34        False     4
8   Sophia   20  2.13        False     1
9   Daniel   20  3.90        False     2
10    Noah   20  3.93        False     3
11  Olivia   20  3.62        False     4
12   Lucas   18  2.61        False     1
13   Grace   20  2.20        False     2
14   Henry   19  3.37        False     3
15    Liam   18  2.88        False     4
16     Ava   19  2.24        False     1
17     Mia   19  2.99        False     2
18  Nathan   19  2.07        False     3
19   Chloe   19  3.82        False     4
20   Alice   19  3.85        False     3

#### 5.9. Updating an Entire Column

We can update the entire column by replacing it with a new list of values. This is useful when you need to modify all entries in a column based on new data or calculations.

In [18]:
# Assigning a value to a column replaces every value in that column.
df_update = df_new.copy()
df_update["Major"] = "CSC"

df_update

      Name  Age   GPA  Scholarship  Year Major
0    James   20  2.91        False     1   CSC
1    Chris   18  3.57        False     2   CSC
2     Adam   20  2.40        False     3   CSC
3   Marian   20  3.03        False     4   CSC
4    Peter   18  3.18        False     1   CSC
5    Kevin   18  2.09        False     2   CSC
6    Linda   20  3.22        False     3   CSC
7     Emma   19  2.34        False     4   CSC
8   Sophia   20  2.13        False     1   CSC
9   Daniel   20  3.90        False     2   CSC
10    Noah   20  3.93        False     3   CSC
11  Olivia   20  3.62        False     4   CSC
12   Lucas   18  2.61        False     1   CSC
13   Grace   20  2.20        False     2   CSC
14   Henry   19  3.37        False     3   CSC
15    Liam   18  2.88        False     4   CSC
16     Ava   19  2.24        False     1   CSC
17     Mia   19  2.99        False     2   CSC
18  Nathan   19  2.07        False     3   CSC
19   Chloe   19  3.82        False     4   CSC
20   Alice   19  3.85        False     3   CSC

In [19]:
# You can also assign a list or Series.
df_update["Age"] = np.random.randint(18, 21, len(df_update))
df_update

      Name  Age   GPA  Scholarship  Year Major
0    James   19  2.91        False     1   CSC
1    Chris   19  3.57        False     2   CSC
2     Adam   19  2.40        False     3   CSC
3   Marian   19  3.03        False     4   CSC
4    Peter   19  3.18        False     1   CSC
5    Kevin   19  2.09        False     2   CSC
6    Linda   19  3.22        False     3   CSC
7     Emma   18  2.34        False     4   CSC
8   Sophia   20  2.13        False     1   CSC
9   Daniel   19  3.90        False     2   CSC
10    Noah   19  3.93        False     3   CSC
11  Olivia   19  3.62        False     4   CSC
12   Lucas   19  2.61        False     1   CSC
13   Grace   19  2.20        False     2   CSC
14   Henry   19  3.37        False     3   CSC
15    Liam   20  2.88        False     4   CSC
16     Ava   20  2.24        False     1   CSC
17     Mia   19  2.99        False     2   CSC
18  Nathan   20  2.07        False     3   CSC
19   Chloe   18  3.82        False     4   CSC
20   Alice   19  3.85        False     3   CSC

#### 5.10. Updating Specific Rows

Updating specific rows in a DataFrame can be done by using boolean indexing or the `loc` method to target specific rows based on conditions. This allows for precise modifications to the dataset.

In [20]:
# award a scholarship to students with a GPA of at least 3.5
df_update["Scholarship"] = False
df_update.loc[df_update["GPA"] >= 3.5, "Scholarship"] = True

df_update[df_update["GPA"] >= 3.5]

      Name  Age   GPA  Scholarship  Year Major
1    Chris   19  3.57         True     2   CSC
9   Daniel   19  3.90         True     2   CSC
10    Noah   19  3.93         True     3   CSC
11  Olivia   19  3.62         True     4   CSC
19   Chloe   18  3.82         True     4   CSC
20   Alice   19  3.85         True     3   CSC

#### 5.11. Updating a DataFrame Using Filtering

Filtering is commonly used to update a DataFrame based on specific conditions. By applying filters, you can selectively modify rows that meet certain criteria, enabling targeted data manipulation.

Note that it only returns the rows that meet the specified conditions, allowing for efficient updates to the dataset without affecting unrelated data.

In [21]:
# Filtering is commonly used to create a new DataFrame containing only selected rows.
high_gpa = df_new[df_new["GPA"] >= 3.5]
high_gpa

      Name  Age   GPA  Scholarship  Year
1    Chris   18  3.57        False     2
9   Daniel   20  3.90        False     2
10    Noah   20  3.93        False     3
11  Olivia   20  3.62        False     4
19   Chloe   19  3.82        False     4
20   Alice   19  3.85        False     3