## Data Analytics

### Chapter 9: Data Combination (Merging and Joining)

Merging is the process of combining two or more datasets based on a common key or identifier. It allows analysts to bring together information from different sources to create a more comprehensive dataset for analysis.

Joining is a specific type of merging that involves combining datasets based on a shared attribute or column.

#### Generate Synthetic Data

In [77]:
import numpy as np
import pandas as pd

np.random.seed(42)

- Student Dataset

In [78]:
names = [
    "James", "Chris", "Adam", "Marian", "Peter",
    "Kevin", "Linda", "Emma", "Sophia", "Daniel",
    "Noah", "Olivia", "Lucas", "Grace", "Henry",
    "Liam", "Ava", "Mia", "Nathan", "Chloe"
]

majors = ["AI", "IT", "CSC", "SW"]
gender = ["Male", "Female"]

n = 20

students = pd.DataFrame({
    "StudentID": range(1001, 1001+n),
    "Name": names,
    "Gender": np.random.choice(gender, n),
    "Age": np.random.randint(18, 22, n),
    "Major": np.random.choice(majors, n),
    "GPA": np.round(np.random.uniform(2.0, 4.0, n), 2)
})

students

    StudentID    Name  Gender  Age Major   GPA
0        1001   James    Male   19   CSC  3.22
1        1002   Chris  Female   18   CSC  2.34
2        1003    Adam    Male   19    IT  2.13
3        1004  Marian    Male   21    SW  3.90
4        1005   Peter    Male   21    SW  3.93
5        1006   Kevin  Female   19    SW  3.62
6        1007   Linda    Male   19    SW  2.61
7        1008    Emma    Male   19   CSC  2.20
8        1009  Sophia    Male   21    IT  3.37
9        1010  Daniel  Female   21    IT  2.88
10       1011    Noah    Male   18   CSC  2.24
11       1012  Olivia    Male   18    IT  2.99
12       1013   Lucas    Male   21   CSC  2.07
13       1014   Grace    Male   19    SW  3.82
14       1015   Henry  Female   19   CSC  2.52
15       1016    Liam    Male   18    SW  3.33
16       1017     Ava  Female   21    SW  2.62
17       1018     Mia  Female   18    AI  3.04
18       1019  Nathan  Female   18   CSC  3.09
19       1020   Chloe    Male   20    AI  2.37

- Instructor Dataset

In [79]:
instructors = pd.DataFrame({
    "InstructorID": [101,102,103,104,105],
    "Instructor": [
        "Dr. Smith",
        "Dr. Johnson",
        "Dr. Lee",
        "Dr. Brown",
        "Dr. Davis"
    ],
    "Age": [45, 52, 38, 41, 50],
    "Gender": ["Male","Female","Female","Male","Male"]
})

instructors

   InstructorID   Instructor  Age  Gender
0           101    Dr. Smith   45    Male
1           102  Dr. Johnson   52  Female
2           103      Dr. Lee   38  Female
3           104    Dr. Brown   41    Male
4           105    Dr. Davis   50    Male

- Course Dataset

In [80]:
courses = pd.DataFrame({
    "CourseID": [1,2,3,4,5,6],
    "Course": [
        "Machine Learning",
        "Basic Programming",
        "Data Analytics",
        "Software Engineering",
        "Computer Vision",
        "Web Development"
    ],
    "Major": ["AI","IT","CSC","SW","AI","IT"],
    "Semester": [1,1,2,2,2,1],
    "Time": [
        "Mon 08:00",
        "Tue 10:00",
        "Wed 13:00",
        "Thu 09:00",
        "Fri 14:00",
        "Fri 08:00"
    ],
    "InstructorID": [101,102,103,104,105,102]
})

courses

   CourseID                Course Major  Semester       Time  InstructorID
0         1      Machine Learning    AI         1  Mon 08:00           101
1         2     Basic Programming    IT         1  Tue 10:00           102
2         3        Data Analytics   CSC         2  Wed 13:00           103
3         4  Software Engineering    SW         2  Thu 09:00           104
4         5       Computer Vision    AI         2  Fri 14:00           105
5         6       Web Development    IT         1  Fri 08:00           102

#### 9.1. Inner Merge

An **inner merge** returns only the rows that have matching values in both DataFrames.

In [81]:
result = students.merge(courses, on="Major", how="inner")
result

,StudentID,Name,Gender,Age,Major,GPA,CourseID,Course,Semester,Time,InstructorID
0,1001,James,Male,19,CSC,3.22,3,Data Analytics,2,Wed 13:00,103
1,1002,Chris,Female,18,CSC,2.34,3,Data Analytics,2,Wed 13:00,103
2,1003,Adam,Male,19,IT,2.13,2,Basic Programming,1,Tue 10:00,102
3,1003,Adam,Male,19,IT,2.13,6,Web Development,1,Fri 08:00,102
4,1004,Marian,Male,21,SW,3.90,4,Software Engineering,2,Thu 09:00,104
5,1005,Peter,Male,21,SW,3.93,4,Software Engineering,2,Thu 09:00,104
6,1006,Kevin,Female,19,SW,3.62,4,Software Engineering,2,Thu 09:00,104
7,1007,Linda,Male,19,SW,2.61,4,Software Engineering,2,Thu 09:00,104
8,1008,Emma,Male,19,CSC,2.20,3,Data Analytics,2,Wed 13:00,103
9,1009,Sophia,Male,21,IT,3.37,2,Basic Programming,1,Tue 10:00,102
10,1009,Sophia,Male,21,IT,3.37,6,Web Development,1,Fri 08:00,102
11,1010,Daniel,Female,21,IT,2.88,2,Basic Programming,1,Tue 10:00,102
12,1010,Daniel,Female,21,IT,2.88,6,Web Development,1,Fri 08:00,102
13,1011,Noah,Male,18,CSC,2.24,3,Data Analytics,2,Wed 13:00,103
14,1012,Olivia,Male,18,IT,2.99,2,Basic Programming,1,Tue 10:00,102
15,1012,Olivia,Male,18,IT,2.99,6,Web Development,1,Fri 08:00,102
16,1013,Lucas,Male,21,CSC,2.07,3,Data Analytics,2,Wed 13:00,103
17,1014,Grace,Male,19,SW,3.82,4,Software Engineering,2,Thu 09:00,104
18,1015,Henry,Female,19,CSC,2.52,3,Data Analytics,2,Wed 13:00,103
19,1016,Liam,Male,18,SW,3.33,4,Software Engineering,2,Thu 09:00,104
20,1017,Ava,Female,21,SW,2.62,4,Software Engineering,2,Thu 09:00,104
21,1018,Mia,Female,18,AI,3.04,1,Machine Learning,1,Mon 08:00,101
22,1018,Mia,Female,18,AI,3.04,5,Computer Vision,2,Fri 14:00,105
23,1019,Nathan,Female,18,CSC,3.09,3,Data Analytics,2,Wed 13:00,103
24,1020,Chloe,Male,20,AI,2.37,1,Machine Learning,1,Mon 08:00,101
25,1020,Chloe,Male,20,AI,2.37,5,Computer Vision,2,Fri 14:00,105

#### 9.2. Left Merge

A **left merge** keeps every row from the left DataFrame. If no matching row exists in the right DataFrame, the missing values are filled with `NaN`.

In [82]:
result = students.merge(courses, on="Major", how="left")
result

,StudentID,Name,Gender,Age,Major,GPA,CourseID,Course,Semester,Time,InstructorID
0,1001,James,Male,19,CSC,3.22,3,Data Analytics,2,Wed 13:00,103
1,1002,Chris,Female,18,CSC,2.34,3,Data Analytics,2,Wed 13:00,103
2,1003,Adam,Male,19,IT,2.13,2,Basic Programming,1,Tue 10:00,102
3,1003,Adam,Male,19,IT,2.13,6,Web Development,1,Fri 08:00,102
4,1004,Marian,Male,21,SW,3.90,4,Software Engineering,2,Thu 09:00,104
5,1005,Peter,Male,21,SW,3.93,4,Software Engineering,2,Thu 09:00,104
6,1006,Kevin,Female,19,SW,3.62,4,Software Engineering,2,Thu 09:00,104
7,1007,Linda,Male,19,SW,2.61,4,Software Engineering,2,Thu 09:00,104
8,1008,Emma,Male,19,CSC,2.20,3,Data Analytics,2,Wed 13:00,103
9,1009,Sophia,Male,21,IT,3.37,2,Basic Programming,1,Tue 10:00,102
10,1009,Sophia,Male,21,IT,3.37,6,Web Development,1,Fri 08:00,102
11,1010,Daniel,Female,21,IT,2.88,2,Basic Programming,1,Tue 10:00,102
12,1010,Daniel,Female,21,IT,2.88,6,Web Development,1,Fri 08:00,102
13,1011,Noah,Male,18,CSC,2.24,3,Data Analytics,2,Wed 13:00,103
14,1012,Olivia,Male,18,IT,2.99,2,Basic Programming,1,Tue 10:00,102
15,1012,Olivia,Male,18,IT,2.99,6,Web Development,1,Fri 08:00,102
16,1013,Lucas,Male,21,CSC,2.07,3,Data Analytics,2,Wed 13:00,103
17,1014,Grace,Male,19,SW,3.82,4,Software Engineering,2,Thu 09:00,104
18,1015,Henry,Female,19,CSC,2.52,3,Data Analytics,2,Wed 13:00,103
19,1016,Liam,Male,18,SW,3.33,4,Software Engineering,2,Thu 09:00,104
20,1017,Ava,Female,21,SW,2.62,4,Software Engineering,2,Thu 09:00,104
21,1018,Mia,Female,18,AI,3.04,1,Machine Learning,1,Mon 08:00,101
22,1018,Mia,Female,18,AI,3.04,5,Computer Vision,2,Fri 14:00,105
23,1019,Nathan,Female,18,CSC,3.09,3,Data Analytics,2,Wed 13:00,103
24,1020,Chloe,Male,20,AI,2.37,1,Machine Learning,1,Mon 08:00,101
25,1020,Chloe,Male,20,AI,2.37,5,Computer Vision,2,Fri 14:00,105

#### 9.3. Right Merge

A **right merge** keeps every row from the right DataFrame.

In [83]:
result = students.merge(courses, on="Major", how="right")
result

,StudentID,Name,Gender,Age,Major,GPA,CourseID,Course,Semester,Time,InstructorID
0,1018,Mia,Female,18,AI,3.04,1,Machine Learning,1,Mon 08:00,101
1,1020,Chloe,Male,20,AI,2.37,1,Machine Learning,1,Mon 08:00,101
2,1003,Adam,Male,19,IT,2.13,2,Basic Programming,1,Tue 10:00,102
3,1009,Sophia,Male,21,IT,3.37,2,Basic Programming,1,Tue 10:00,102
4,1010,Daniel,Female,21,IT,2.88,2,Basic Programming,1,Tue 10:00,102
5,1012,Olivia,Male,18,IT,2.99,2,Basic Programming,1,Tue 10:00,102
6,1001,James,Male,19,CSC,3.22,3,Data Analytics,2,Wed 13:00,103
7,1002,Chris,Female,18,CSC,2.34,3,Data Analytics,2,Wed 13:00,103
8,1008,Emma,Male,19,CSC,2.20,3,Data Analytics,2,Wed 13:00,103
9,1011,Noah,Male,18,CSC,2.24,3,Data Analytics,2,Wed 13:00,103
10,1013,Lucas,Male,21,CSC,2.07,3,Data Analytics,2,Wed 13:00,103
11,1015,Henry,Female,19,CSC,2.52,3,Data Analytics,2,Wed 13:00,103
12,1019,Nathan,Female,18,CSC,3.09,3,Data Analytics,2,Wed 13:00,103
13,1004,Marian,Male,21,SW,3.90,4,Software Engineering,2,Thu 09:00,104
14,1005,Peter,Male,21,SW,3.93,4,Software Engineering,2,Thu 09:00,104
15,1006,Kevin,Female,19,SW,3.62,4,Software Engineering,2,Thu 09:00,104
16,1007,Linda,Male,19,SW,2.61,4,Software Engineering,2,Thu 09:00,104
17,1014,Grace,Male,19,SW,3.82,4,Software Engineering,2,Thu 09:00,104
18,1016,Liam,Male,18,SW,3.33,4,Software Engineering,2,Thu 09:00,104
19,1017,Ava,Female,21,SW,2.62,4,Software Engineering,2,Thu 09:00,104
20,1018,Mia,Female,18,AI,3.04,5,Computer Vision,2,Fri 14:00,105
21,1020,Chloe,Male,20,AI,2.37,5,Computer Vision,2,Fri 14:00,105
22,1003,Adam,Male,19,IT,2.13,6,Web Development,1,Fri 08:00,102
23,1009,Sophia,Male,21,IT,3.37,6,Web Development,1,Fri 08:00,102
24,1010,Daniel,Female,21,IT,2.88,6,Web Development,1,Fri 08:00,102
25,1012,Olivia,Male,18,IT,2.99,6,Web Development,1,Fri 08:00,102

#### 9.4. Outer Merge

An **outer merge** keeps every row from both DataFrames. Rows without matches are filled with `NaN`.

In [84]:
result = students.merge(courses, on="Major", how="outer")
result

,StudentID,Name,Gender,Age,Major,GPA,CourseID,Course,Semester,Time,InstructorID
0,1018,Mia,Female,18,AI,3.04,1,Machine Learning,1,Mon 08:00,101
1,1018,Mia,Female,18,AI,3.04,5,Computer Vision,2,Fri 14:00,105
2,1020,Chloe,Male,20,AI,2.37,1,Machine Learning,1,Mon 08:00,101
3,1020,Chloe,Male,20,AI,2.37,5,Computer Vision,2,Fri 14:00,105
4,1001,James,Male,19,CSC,3.22,3,Data Analytics,2,Wed 13:00,103
5,1002,Chris,Female,18,CSC,2.34,3,Data Analytics,2,Wed 13:00,103
6,1008,Emma,Male,19,CSC,2.20,3,Data Analytics,2,Wed 13:00,103
7,1011,Noah,Male,18,CSC,2.24,3,Data Analytics,2,Wed 13:00,103
8,1013,Lucas,Male,21,CSC,2.07,3,Data Analytics,2,Wed 13:00,103
9,1015,Henry,Female,19,CSC,2.52,3,Data Analytics,2,Wed 13:00,103
10,1019,Nathan,Female,18,CSC,3.09,3,Data Analytics,2,Wed 13:00,103
11,1003,Adam,Male,19,IT,2.13,2,Basic Programming,1,Tue 10:00,102
12,1003,Adam,Male,19,IT,2.13,6,Web Development,1,Fri 08:00,102
13,1009,Sophia,Male,21,IT,3.37,2,Basic Programming,1,Tue 10:00,102
14,1009,Sophia,Male,21,IT,3.37,6,Web Development,1,Fri 08:00,102
15,1010,Daniel,Female,21,IT,2.88,2,Basic Programming,1,Tue 10:00,102
16,1010,Daniel,Female,21,IT,2.88,6,Web Development,1,Fri 08:00,102
17,1012,Olivia,Male,18,IT,2.99,2,Basic Programming,1,Tue 10:00,102
18,1012,Olivia,Male,18,IT,2.99,6,Web Development,1,Fri 08:00,102
19,1004,Marian,Male,21,SW,3.90,4,Software Engineering,2,Thu 09:00,104
20,1005,Peter,Male,21,SW,3.93,4,Software Engineering,2,Thu 09:00,104
21,1006,Kevin,Female,19,SW,3.62,4,Software Engineering,2,Thu 09:00,104
22,1007,Linda,Male,19,SW,2.61,4,Software Engineering,2,Thu 09:00,104
23,1014,Grace,Male,19,SW,3.82,4,Software Engineering,2,Thu 09:00,104
24,1016,Liam,Male,18,SW,3.33,4,Software Engineering,2,Thu 09:00,104
25,1017,Ava,Female,21,SW,2.62,4,Software Engineering,2,Thu 09:00,104

#### 9.5. Merging on Multiple Columns

Sometimes one column is not sufficient to uniquely identify matching records. In this case, multiple columns can be used.

In [85]:
student2 = students.copy()

student2["Advisor"] = np.random.choice(
    ["Dr. Smith", "Dr. Johnson"],
    len(student2)
)

advisor = student2[["Major", "Advisor"]].drop_duplicates()

result = student2.merge(
    advisor,
    on=["Major", "Advisor"],
    how="inner"
)

result

    StudentID    Name  Gender  Age Major   GPA      Advisor
0        1001   James    Male   19   CSC  3.22    Dr. Smith
1        1002   Chris  Female   18   CSC  2.34  Dr. Johnson
2        1003    Adam    Male   19    IT  2.13  Dr. Johnson
3        1004  Marian    Male   21    SW  3.90  Dr. Johnson
4        1005   Peter    Male   21    SW  3.93  Dr. Johnson
5        1006   Kevin  Female   19    SW  3.62  Dr. Johnson
6        1007   Linda    Male   19    SW  2.61  Dr. Johnson
7        1008    Emma    Male   19   CSC  2.20  Dr. Johnson
8        1009  Sophia    Male   21    IT  3.37  Dr. Johnson
9        1010  Daniel  Female   21    IT  2.88    Dr. Smith
10       1011    Noah    Male   18   CSC  2.24  Dr. Johnson
11       1012  Olivia    Male   18    IT  2.99    Dr. Smith
12       1013   Lucas    Male   21   CSC  2.07  Dr. Johnson
13       1014   Grace    Male   19    SW  3.82  Dr. Johnson
14       1015   Henry  Female   19   CSC  2.52    Dr. Smith
15       1016    Liam    Male   18    SW  3.33  Dr. Johnson
16       1017     Ava  Female   21    SW  2.62    Dr. Smith
17       1018     Mia  Female   18    AI  3.04  Dr. Johnson
18       1019  Nathan  Female   18   CSC  3.09  Dr. Johnson
19       1020   Chloe    Male   20    AI  2.37    Dr. Smith

#### 9.6. Merging with Different Column Names

The matching columns do not need to have the same name. Use the `left_on` and `right_on` parameters.

In [86]:
courses2 = courses.rename(columns={
    "InstructorID": "ID"})

result = instructors.merge(
    courses2,
    left_on="InstructorID",
    right_on="ID",
    how="inner"
)

result

,InstructorID,Instructor,Age,Gender,CourseID,Course,Major,Semester,Time,ID
0,101,Dr. Smith,45,Male,1,Machine Learning,AI,1,Mon 08:00,101
1,102,Dr. Johnson,52,Female,2,Basic Programming,IT,1,Tue 10:00,102
2,102,Dr. Johnson,52,Female,6,Web Development,IT,1,Fri 08:00,102
3,103,Dr. Lee,38,Female,3,Data Analytics,CSC,2,Wed 13:00,103
4,104,Dr. Brown,41,Male,4,Software Engineering,SW,2,Thu 09:00,104
5,105,Dr. Davis,50,Male,5,Computer Vision,AI,2,Fri 14:00,105

#### 9.7. Merging Three DataFrames

Multiple DataFrames can be merged sequentially by nesting `merge()` operations.

In [87]:
result = (students
        .merge(courses, on="Major", how="left")
        .merge(instructors, on="InstructorID", how="left")
)

result

,StudentID,Name,Gender_x,Age_x,Major,GPA,CourseID,Course,Semester,Time,InstructorID,Instructor,Age_y,Gender_y
0,1001,James,Male,19,CSC,3.22,3,Data Analytics,2,Wed 13:00,103,Dr. Lee,38,Female
1,1002,Chris,Female,18,CSC,2.34,3,Data Analytics,2,Wed 13:00,103,Dr. Lee,38,Female
2,1003,Adam,Male,19,IT,2.13,2,Basic Programming,1,Tue 10:00,102,Dr. Johnson,52,Female
3,1003,Adam,Male,19,IT,2.13,6,Web Development,1,Fri 08:00,102,Dr. Johnson,52,Female
4,1004,Marian,Male,21,SW,3.90,4,Software Engineering,2,Thu 09:00,104,Dr. Brown,41,Male
5,1005,Peter,Male,21,SW,3.93,4,Software Engineering,2,Thu 09:00,104,Dr. Brown,41,Male
6,1006,Kevin,Female,19,SW,3.62,4,Software Engineering,2,Thu 09:00,104,Dr. Brown,41,Male
7,1007,Linda,Male,19,SW,2.61,4,Software Engineering,2,Thu 09:00,104,Dr. Brown,41,Male
8,1008,Emma,Male,19,CSC,2.20,3,Data Analytics,2,Wed 13:00,103,Dr. Lee,38,Female
9,1009,Sophia,Male,21,IT,3.37,2,Basic Programming,1,Tue 10:00,102,Dr. Johnson,52,Female
10,1009,Sophia,Male,21,IT,3.37,6,Web Development,1,Fri 08:00,102,Dr. Johnson,52,Female
11,1010,Daniel,Female,21,IT,2.88,2,Basic Programming,1,Tue 10:00,102,Dr. Johnson,52,Female
12,1010,Daniel,Female,21,IT,2.88,6,Web Development,1,Fri 08:00,102,Dr. Johnson,52,Female
13,1011,Noah,Male,18,CSC,2.24,3,Data Analytics,2,Wed 13:00,103,Dr. Lee,38,Female
14,1012,Olivia,Male,18,IT,2.99,2,Basic Programming,1,Tue 10:00,102,Dr. Johnson,52,Female
15,1012,Olivia,Male,18,IT,2.99,6,Web Development,1,Fri 08:00,102,Dr. Johnson,52,Female
16,1013,Lucas,Male,21,CSC,2.07,3,Data Analytics,2,Wed 13:00,103,Dr. Lee,38,Female
17,1014,Grace,Male,19,SW,3.82,4,Software Engineering,2,Thu 09:00,104,Dr. Brown,41,Male
18,1015,Henry,Female,19,CSC,2.52,3,Data Analytics,2,Wed 13:00,103,Dr. Lee,38,Female
19,1016,Liam,Male,18,SW,3.33,4,Software Engineering,2,Thu 09:00,104,Dr. Brown,41,Male
20,1017,Ava,Female,21,SW,2.62,4,Software Engineering,2,Thu 09:00,104,Dr. Brown,41,Male
21,1018,Mia,Female,18,AI,3.04,1,Machine Learning,1,Mon 08:00,101,Dr. Smith,45,Male
22,1018,Mia,Female,18,AI,3.04,5,Computer Vision,2,Fri 14:00,105,Dr. Davis,50,Male
23,1019,Nathan,Female,18,CSC,3.09,3,Data Analytics,2,Wed 13:00,103,Dr. Lee,38,Female
24,1020,Chloe,Male,20,AI,2.37,1,Machine Learning,1,Mon 08:00,101,Dr. Smith,45,Male
25,1020,Chloe,Male,20,AI,2.37,5,Computer Vision,2,Fri 14:00,105,Dr. Davis,50,Male

#### Setting the Index

Now we move on to joining. Before joining, set the ID columns as the index.

In [88]:
student_idx = students.set_index("StudentID")
course_idx = courses.set_index("InstructorID")
instructor_idx = instructors.set_index("InstructorID")

#### 9.8. Basic Join

The simplest usage joins two DataFrames using their indexes.

In [89]:
result = course_idx.join(instructor_idx)
result

,CourseID,Course,Major,Semester,Time,Instructor,Age,Gender
InstructorID,,,,,,,,
101,1,Machine Learning,AI,1,Mon 08:00,Dr. Smith,45,Male
102,2,Basic Programming,IT,1,Tue 10:00,Dr. Johnson,52,Female
103,3,Data Analytics,CSC,2,Wed 13:00,Dr. Lee,38,Female
104,4,Software Engineering,SW,2,Thu 09:00,Dr. Brown,41,Male
105,5,Computer Vision,AI,2,Fri 14:00,Dr. Davis,50,Male
102,6,Web Development,IT,1,Fri 08:00,Dr. Johnson,52,Female

#### 9.9. Left Join

By default, `join()` performs a **left join**, preserving all rows from the calling DataFrame.

In [90]:
result = course_idx.join(
		instructor_idx,
        how="left"
)

result

,CourseID,Course,Major,Semester,Time,Instructor,Age,Gender
InstructorID,,,,,,,,
101,1,Machine Learning,AI,1,Mon 08:00,Dr. Smith,45,Male
102,2,Basic Programming,IT,1,Tue 10:00,Dr. Johnson,52,Female
103,3,Data Analytics,CSC,2,Wed 13:00,Dr. Lee,38,Female
104,4,Software Engineering,SW,2,Thu 09:00,Dr. Brown,41,Male
105,5,Computer Vision,AI,2,Fri 14:00,Dr. Davis,50,Male
102,6,Web Development,IT,1,Fri 08:00,Dr. Johnson,52,Female

#### 9.10. Inner Join

Only rows with matching indexes are returned.

In [91]:
result = course_idx.join(
    instructor_idx,
    how="inner"
)

result

,CourseID,Course,Major,Semester,Time,Instructor,Age,Gender
InstructorID,,,,,,,,
101,1,Machine Learning,AI,1,Mon 08:00,Dr. Smith,45,Male
102,2,Basic Programming,IT,1,Tue 10:00,Dr. Johnson,52,Female
103,3,Data Analytics,CSC,2,Wed 13:00,Dr. Lee,38,Female
104,4,Software Engineering,SW,2,Thu 09:00,Dr. Brown,41,Male
105,5,Computer Vision,AI,2,Fri 14:00,Dr. Davis,50,Male
102,6,Web Development,IT,1,Fri 08:00,Dr. Johnson,52,Female

#### 9.11. Right Join

Keep all rows from the second DataFrame.

In [92]:
result = course_idx.join(
    instructor_idx,
    how="right"
)

result

,CourseID,Course,Major,Semester,Time,Instructor,Age,Gender
InstructorID,,,,,,,,
101,1,Machine Learning,AI,1,Mon 08:00,Dr. Smith,45,Male
102,2,Basic Programming,IT,1,Tue 10:00,Dr. Johnson,52,Female
102,6,Web Development,IT,1,Fri 08:00,Dr. Johnson,52,Female
103,3,Data Analytics,CSC,2,Wed 13:00,Dr. Lee,38,Female
104,4,Software Engineering,SW,2,Thu 09:00,Dr. Brown,41,Male
105,5,Computer Vision,AI,2,Fri 14:00,Dr. Davis,50,Male

### 9.12. Outer Join

Keep every index from both DataFrames.

In [93]:
result = course_idx.join(
    instructor_idx,
    how="outer"
)

result

,CourseID,Course,Major,Semester,Time,Instructor,Age,Gender
InstructorID,,,,,,,,
101,1,Machine Learning,AI,1,Mon 08:00,Dr. Smith,45,Male
102,2,Basic Programming,IT,1,Tue 10:00,Dr. Johnson,52,Female
102,6,Web Development,IT,1,Fri 08:00,Dr. Johnson,52,Female
103,3,Data Analytics,CSC,2,Wed 13:00,Dr. Lee,38,Female
104,4,Software Engineering,SW,2,Thu 09:00,Dr. Brown,41,Male
105,5,Computer Vision,AI,2,Fri 14:00,Dr. Davis,50,Male

#### 9.13. Joining Multiple DataFrames

Like `merge()`, `join()` can combine multiple DataFrames in a single operation.

In [94]:
result = (course_idx
          .join(instructor_idx, rsuffix="_Instructor")
          .join(student_idx, rsuffix="_Student"))

result

,CourseID,Course,Major,Semester,Time,Instructor,Age,Gender,Name,Gender_Student,Age_Student,Major_Student,GPA
InstructorID,,,,,,,,,,,,,
101,1,Machine Learning,AI,1,Mon 08:00,Dr. Smith,45,Male,NaN,NaN,NaN,NaN,NaN
102,2,Basic Programming,IT,1,Tue 10:00,Dr. Johnson,52,Female,NaN,NaN,NaN,NaN,NaN
103,3,Data Analytics,CSC,2,Wed 13:00,Dr. Lee,38,Female,NaN,NaN,NaN,NaN,NaN
104,4,Software Engineering,SW,2,Thu 09:00,Dr. Brown,41,Male,NaN,NaN,NaN,NaN,NaN
105,5,Computer Vision,AI,2,Fri 14:00,Dr. Davis,50,Male,NaN,NaN,NaN,NaN,NaN
102,6,Web Development,IT,1,Fri 08:00,Dr. Johnson,52,Female,NaN,NaN,NaN,NaN,NaN

In [95]:
# multiple DataFrames can be passed as a list when they share the same index.
df1 = student_idx[["Name", "Major"]]
df2 = student_idx[["Age", "GPA"]]

result = df1.join(df2)

result

             Name Major  Age   GPA
StudentID
1001        James   CSC   19  3.22
1002        Chris   CSC   18  2.34
1003         Adam    IT   19  2.13
1004       Marian    SW   21  3.90
1005        Peter    SW   21  3.93
1006        Kevin    SW   19  3.62
1007        Linda    SW   19  2.61
1008         Emma   CSC   19  2.20
1009       Sophia    IT   21  3.37
1010       Daniel    IT   21  2.88
1011         Noah   CSC   18  2.24
1012       Olivia    IT   18  2.99
1013        Lucas   CSC   21  2.07
1014        Grace    SW   19  3.82
1015        Henry   CSC   19  2.52
1016         Liam    SW   18  3.33
1017          Ava    SW   21  2.62
1018          Mia    AI   18  3.04
1019       Nathan   CSC   18  3.09
1020        Chloe    AI   20  2.37