## Data Analytics

### Chapter 2: Data Subsetting (Indexing & Slicing)

Data subsetting is a fundamental step in data analysis, allowing you to focus on specific portions of your dataset for more targeted insights. This chapter explores various techniques for subsetting data effectively.

- **Length, Shape and Size**: Understanding the dimensions of your dataset to determine how many rows and columns it contains.
- **Indexing**: Methods to access specific rows and columns in your dataset using labels or integer-based positions.
- **Slicing**: Techniques to extract a range of rows or columns from your dataset for focused analysis.

#### Generate Synthetic Data

In [15]:
import numpy as np
import pandas as pd

# Reproducible randomness
np.random.seed(42)

In [16]:
names = [
    "James", "Chris", "Adam", "Marian", "Peter",
    "Kevin", "Linda", "Emma", "Sophia", "Daniel",
    "Noah", "Olivia", "Lucas", "Grace", "Henry",
    "Liam", "Ava", "Mia", "Nathan", "Chloe"
]

majors = ["AI", "IT", "CSC", "SW"]

n = 20

df = pd.DataFrame({
    "Name": np.array(names),
    "Age": np.random.randint(18, 21, n),
    "Major": np.random.choice(majors, n),
    "GPA": np.round(np.random.uniform(2.0, 4.0, n), 2)
})

df

      Name  Age Major   GPA
0    James   20    SW  2.91
1    Chris   18    SW  3.57
2     Adam   20    AI  2.40
3   Marian   20    AI  3.03
4    Peter   18    SW  3.18
5    Kevin   18    IT  2.09
6    Linda   20    IT  3.22
7     Emma   19    AI  2.34
8   Sophia   20    SW  2.13
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
11  Olivia   20   CSC  3.62
12   Lucas   18   CSC  2.61
13   Grace   20   CSC  2.20
14   Henry   19    IT  3.37
15    Liam   18    SW  2.88
16     Ava   19    SW  2.24
17     Mia   19    SW  2.99
18  Nathan   19    SW  2.07
19   Chloe   19   CSC  3.82

#### 2.1. Data Length, Shape and Size

You can use the `len()`, `shape`, and `size` attributes to get information about the dimensions of your dataset.

In [17]:
# Retrieve Length, Size, and Shape of data
print("Number of Samples:", len(df))
print("Number of Columns:", len(df.columns))

Number of Samples: 20
Number of Columns: 4

In [18]:
# Counting Unique Values
print("Unique Values in Major column:", df["Major"].unique())
print("Number of Unique Values in Major column:", len(df["Major"].unique()))

Unique Values in Major column: ['SW' 'AI' 'IT' 'CSC']
Number of Unique Values in Major column: 4

In [19]:
# Calculate average
# You can also use sum(df["GPA"]) / len(df) 
average_gpa = sum(df["GPA"]) / len(df["GPA"]) 
print('Average GPA:', average_gpa)

Average GPA: 2.925

In [20]:
print("DataFrame Shape:", df.shape)
print(" + Rows:", df.shape[0])
print(" + Columns:", df.shape[1])
print("DataFrame Size:", df.size)

DataFrame Shape: (20, 4)
 + Rows: 20
 + Columns: 4
DataFrame Size: 80

#### 2.2. Data Indexing and Slicing

Some common types of indexing and slicing include:

- Using column names to access specific columns.

- Integer-based indexing to access specific rows or columns.

- Label-based indexing to access specific rows or columns using labels.

In [21]:
# Size of Rows and Columns
print("Size of Column GPA:", df["GPA"].size)
print("Size of Rows:", df.iloc[0].size)

Size of Column GPA: 20
Size of Rows: 4

In [22]:
# Retrieve the first five students
df.iloc[:5]

     Name  Age Major   GPA
0   James   20    SW  2.91
1   Chris   18    SW  3.57
2    Adam   20    AI  2.40
3  Marian   20    AI  3.03
4   Peter   18    SW  3.18

In [23]:
# Retrieve rows 10–19
df.iloc[10:20]

      Name  Age Major   GPA
10    Noah   20    AI  3.93
11  Olivia   20   CSC  3.62
12   Lucas   18   CSC  2.61
13   Grace   20   CSC  2.20
14   Henry   19    IT  3.37
15    Liam   18    SW  2.88
16     Ava   19    SW  2.24
17     Mia   19    SW  2.99
18  Nathan   19    SW  2.07
19   Chloe   19   CSC  3.82

In [24]:
# Retrieve the Name and GPA columns
df[["Name", "GPA"]]

      Name   GPA
0    James  2.91
1    Chris  3.57
2     Adam  2.40
3   Marian  3.03
4    Peter  3.18
5    Kevin  2.09
6    Linda  3.22
7     Emma  2.34
8   Sophia  2.13
9   Daniel  3.90
10    Noah  3.93
11  Olivia  3.62
12   Lucas  2.61
13   Grace  2.20
14   Henry  3.37
15    Liam  2.88
16     Ava  2.24
17     Mia  2.99
18  Nathan  2.07
19   Chloe  3.82

In [25]:
# Retrieve the first five students and only the Name and Major columns
df.iloc[:5, [0, 2]]

     Name Major
0   James    SW
1   Chris    SW
2    Adam    AI
3  Marian    AI
4   Peter    SW

In [26]:
# Retrieve all GPAs
df.loc[:, "GPA"]

0     2.91
1     3.57
2     2.40
3     3.03
4     3.18
5     2.09
6     3.22
7     2.34
8     2.13
9     3.90
10    3.93
11    3.62
12    2.61
13    2.20
14    3.37
15    2.88
16    2.24
17    2.99
18    2.07
19    3.82
Name: GPA, dtype: float64

In [27]:
# Retrieve all columns except Name
df.iloc[:, 1:]

    Age Major   GPA
0    20    SW  2.91
1    18    SW  3.57
2    20    AI  2.40
3    20    AI  3.03
4    18    SW  3.18
5    18    IT  2.09
6    20    IT  3.22
7    19    AI  2.34
8    20    SW  2.13
9    20    AI  3.90
10   20    AI  3.93
11   20   CSC  3.62
12   18   CSC  2.61
13   20   CSC  2.20
14   19    IT  3.37
15   18    SW  2.88
16   19    SW  2.24
17   19    SW  2.99
18   19    SW  2.07
19   19   CSC  3.82