## Data Analytics

### Chapter 4: Data Manipulation (Replacing & Mapping)

Other than filtering and sorting, data manipulation also includes techniques for replacing existing values with new ones or creating a new dataset based on existing data. This chapter explores various techniques for replacing and mapping data effectively.

**Replacing and Mapping are techniques used in data manipulation to modify or transform data values in a dataset. These techniques are essential for cleaning, standardizing, and preparing data for analysis.**

While they are similar, they serve different purposes:

- **Replacing**: This involves substituting existing values in a dataset with new values. It is often used to correct errors, standardize data, or handle missing values. For example, replacing all instances of "N/A" with `NaN` or changing categorical values like "Yes" and "No" to `1` and `0`, respectively.

- **Mapping**: This involves creating a new dataset or transforming existing data based on a defined mapping or relationship. Mapping is often used to convert categorical variables into numerical representations, create new features, or apply functions to transform data. For example, mapping a list of country names to their corresponding ISO codes or applying a function to calculate the square of numerical values.

#### Generate Synthetic Data

In [43]:
import numpy as np
import pandas as pd

# Reproducible randomness
np.random.seed(42)

In [44]:
names = [
    "James", "Chris", "Adam", "Marian", "Peter",
    "Kevin", "Linda", "Emma", "Sophia", "Daniel",
    "Noah", "Olivia", "Lucas", "Grace", "Henry",
    "Liam", "Ava", "Mia", "Nathan", "Chloe"
]

majors = ["AI", "IT", "CSC", "SW"]

n = 20

df = pd.DataFrame({
    "Name": np.array(names),
    "Age": np.random.randint(18, 21, n),
    "Major": np.random.choice(majors, n),
    "GPA": np.round(np.random.uniform(2.0, 4.0, n), 2)
})

df

      Name  Age Major   GPA
0    James   20    SW  2.91
1    Chris   18    SW  3.57
2     Adam   20    AI  2.40
3   Marian   20    AI  3.03
4    Peter   18    SW  3.18
5    Kevin   18    IT  2.09
6    Linda   20    IT  3.22
7     Emma   19    AI  2.34
8   Sophia   20    SW  2.13
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
11  Olivia   20   CSC  3.62
12   Lucas   18   CSC  2.61
13   Grace   20   CSC  2.20
14   Henry   19    IT  3.37
15    Liam   18    SW  2.88
16     Ava   19    SW  2.24
17     Mia   19    SW  2.99
18  Nathan   19    SW  2.07
19   Chloe   19   CSC  3.82

In [45]:
# Create two temporary datasets for this section
df_replace = df.copy()
df_map = df.copy()

#### 4.1. Replace a Single Value

You can replace a single value in a DataFrame using the `replace()` method. This method allows us to specify the value we want to replace and the new value we want to use.

In [46]:
df_replace["Major"] = df_replace["Major"].replace("CSC", "Computer Science")

df_replace

      Name  Age             Major   GPA
0    James   20                SW  2.91
1    Chris   18                SW  3.57
2     Adam   20                AI  2.40
3   Marian   20                AI  3.03
4    Peter   18                SW  3.18
5    Kevin   18                IT  2.09
6    Linda   20                IT  3.22
7     Emma   19                AI  2.34
8   Sophia   20                SW  2.13
9   Daniel   20                AI  3.90
10    Noah   20                AI  3.93
11  Olivia   20  Computer Science  3.62
12   Lucas   18  Computer Science  2.61
13   Grace   20  Computer Science  2.20
14   Henry   19                IT  3.37
15    Liam   18                SW  2.88
16     Ava   19                SW  2.24
17     Mia   19                SW  2.99
18  Nathan   19                SW  2.07
19   Chloe   19  Computer Science  3.82

#### 4.2. Replace Multiple Values

You can replace multiple values in a DataFrame by passing a dictionary to the `replace()` method. The keys of the dictionary represent the values to be replaced, and the corresponding values represent the new values.

In [47]:
# A dictionary can replace several values at once.
df_replace["Major"] = df_replace["Major"].replace({
    "AI": "Artificial Intelligence",
    "IT": "Information Technology",
    "CSC": "Computer Science",
    "SW": "Software Engineering"
})

df_replace

      Name  Age                    Major   GPA
0    James   20     Software Engineering  2.91
1    Chris   18     Software Engineering  3.57
2     Adam   20  Artificial Intelligence  2.40
3   Marian   20  Artificial Intelligence  3.03
4    Peter   18     Software Engineering  3.18
5    Kevin   18   Information Technology  2.09
6    Linda   20   Information Technology  3.22
7     Emma   19  Artificial Intelligence  2.34
8   Sophia   20     Software Engineering  2.13
9   Daniel   20  Artificial Intelligence  3.90
10    Noah   20  Artificial Intelligence  3.93
11  Olivia   20         Computer Science  3.62
12   Lucas   18         Computer Science  2.61
13   Grace   20         Computer Science  2.20
14   Henry   19   Information Technology  3.37
15    Liam   18     Software Engineering  2.88
16     Ava   19     Software Engineering  2.24
17     Mia   19     Software Engineering  2.99
18  Nathan   19     Software Engineering  2.07
19   Chloe   19         Computer Science  3.82

In [48]:
# You can even replace values across the entire DataFrame if needed.
df_replace1 = df.copy()
df_replace1 = df_replace1.replace({"CSC": "CS", "SW": "SE"})
df_replace1

      Name  Age Major   GPA
0    James   20    SE  2.91
1    Chris   18    SE  3.57
2     Adam   20    AI  2.40
3   Marian   20    AI  3.03
4    Peter   18    SE  3.18
5    Kevin   18    IT  2.09
6    Linda   20    IT  3.22
7     Emma   19    AI  2.34
8   Sophia   20    SE  2.13
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
11  Olivia   20    CS  3.62
12   Lucas   18    CS  2.61
13   Grace   20    CS  2.20
14   Henry   19    IT  3.37
15    Liam   18    SE  2.88
16     Ava   19    SE  2.24
17     Mia   19    SE  2.99
18  Nathan   19    SE  2.07
19   Chloe   19    CS  3.82

#### 4.3. Basic Mapping

Mapping is similar to replacing, but it is often used to create a new dataset or transform existing data based on a defined mapping or relationship. 

The `map()` method allows you to apply a function or a mapping dictionary to a Series, transforming its values accordingly.

In [49]:
major_map = {
    "AI": "Artificial Intelligence",
    "IT": "Information Technology",
    "CSC": "Computer Science",
    "SW": "Software Engineering"
}

df_map["Major"] = df_map["Major"].map(major_map)

df_map

      Name  Age                    Major   GPA
0    James   20     Software Engineering  2.91
1    Chris   18     Software Engineering  3.57
2     Adam   20  Artificial Intelligence  2.40
3   Marian   20  Artificial Intelligence  3.03
4    Peter   18     Software Engineering  3.18
5    Kevin   18   Information Technology  2.09
6    Linda   20   Information Technology  3.22
7     Emma   19  Artificial Intelligence  2.34
8   Sophia   20     Software Engineering  2.13
9   Daniel   20  Artificial Intelligence  3.90
10    Noah   20  Artificial Intelligence  3.93
11  Olivia   20         Computer Science  3.62
12   Lucas   18         Computer Science  2.61
13   Grace   20         Computer Science  2.20
14   Henry   19   Information Technology  3.37
15    Liam   18     Software Engineering  2.88
16     Ava   19     Software Engineering  2.24
17     Mia   19     Software Engineering  2.99
18  Nathan   19     Software Engineering  2.07
19   Chloe   19         Computer Science  3.82

#### 4.4. Label Encoding Example

Mapping can also be used for label encoding, where categorical values are converted into numerical labels. This is particularly useful for machine learning algorithms that require numerical input.

In [50]:
df_map = df.copy()

major_code = {
    "AI": 0,
    "IT": 1,
    "CSC": 2,
    "SW": 3
}

df_map["Major_Code"] = df_map["Major"].map(major_code)
df_map = df_map.drop(columns=["Major"])

df_map

      Name  Age   GPA  Major_Code
0    James   20  2.91           3
1    Chris   18  3.57           3
2     Adam   20  2.40           0
3   Marian   20  3.03           0
4    Peter   18  3.18           3
5    Kevin   18  2.09           1
6    Linda   20  3.22           1
7     Emma   19  2.34           0
8   Sophia   20  2.13           3
9   Daniel   20  3.90           0
10    Noah   20  3.93           0
11  Olivia   20  3.62           2
12   Lucas   18  2.61           2
13   Grace   20  2.20           2
14   Henry   19  3.37           1
15    Liam   18  2.88           3
16     Ava   19  2.24           3
17     Mia   19  2.99           3
18  Nathan   19  2.07           3
19   Chloe   19  3.82           2

#### 4.5. Mapping with `unique()`

In [52]:
df_map = df.copy()
unique_major = df["Major"].unique()

mapping = {
    value: index
    for index, value in enumerate(unique_major)
}

df_map["Major_Code"] = df_map["Major"].map(mapping)
df_map = df_map.drop(columns=["Major"])

df_map

      Name  Age   GPA  Major_Code
0    James   20  2.91           0
1    Chris   18  3.57           0
2     Adam   20  2.40           1
3   Marian   20  3.03           1
4    Peter   18  3.18           0
5    Kevin   18  2.09           2
6    Linda   20  3.22           2
7     Emma   19  2.34           1
8   Sophia   20  2.13           0
9   Daniel   20  3.90           1
10    Noah   20  3.93           1
11  Olivia   20  3.62           3
12   Lucas   18  2.61           3
13   Grace   20  2.20           3
14   Henry   19  3.37           2
15    Liam   18  2.88           0
16     Ava   19  2.24           0
17     Mia   19  2.99           0
18  Nathan   19  2.07           0
19   Chloe   19  3.82           3

#### 4.6. Replacing Missing Values

Missing Values can be anything:

- Some common values like `NaN`; `None` ; `"N/A"` ; `"Unknown"` ;  

- An empty string `""` ; 

- A blank space `" "` ;  

- A placeholder value such as 0 (when 0 is not a valid value)

In [53]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "Name": [
        "James", "Chris", "Adam", "Marian", "Peter",
        "Kevin", "Linda", "Emma", "Sophia", "Daniel"
    ],
    "Major": [
        "AI", "IT", "Unknown", "CSC", None,
        "", "SW", "N/A", "AI", "CSC"
    ],
    "Age": [
        19, 20, 0, 18, np.nan,
        19, None, 20, 18, 0
    ],
    "GPA": [
        3.60, np.nan, 2.90, 0,
        3.10, None, "N/A", 3.80,
        "", 3.20
    ]
})

df.set_index("Name", inplace=True)

df

          Major   Age   GPA
Name
James        AI  19.0   3.6
Chris        IT  20.0   NaN
Adam    Unknown   0.0   2.9
Marian      CSC  18.0     0
Peter      None   NaN   3.1
Kevin            19.0  None
Linda        SW   NaN   N/A
Emma        N/A  20.0   3.8
Sophia       AI  18.0
Daniel      CSC   0.0   3.2

#### 4.7. Standardizing Missing Values

You can use the `replace()` method to standardize missing values in a DataFrame. This is particularly useful when dealing with datasets that have inconsistent representations of missing data. 

By replacing various representations of missing values with a single standard value (e.g., `NaN`), you can simplify data cleaning and analysis.

In [54]:
df_imputed = df.replace({
    "Unknown": np.nan,
    "N/A": np.nan,
    "": np.nan,
    " ": np.nan,
    0: np.nan
})

df_imputed

/var/folders/gc/49grx5f90nv3f12yh4jhhf740000gn/T/ipykernel_8657/3358218478.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_imputed = df.replace({

       Major   Age  GPA
Name
James     AI  19.0  3.6
Chris     IT  20.0  NaN
Adam     NaN   NaN  2.9
Marian   CSC  18.0  NaN
Peter   None   NaN  3.1
Kevin    NaN  19.0  NaN
Linda     SW   NaN  NaN
Emma     NaN  20.0  3.8
Sophia    AI  18.0  NaN
Daniel   CSC   NaN  3.2

#### 4.8. Imputing Missing Values after Standardization

Now we can simply impute the missing values using the `fillna()` method. This method allows us to fill in missing values with a specified value or a calculated statistic (e.g., mean, median, mode) of the column.

In [55]:
# $eplace missing GPAs with the column mean
df_imputed["GPA"] = df_imputed["GPA"].fillna(df_imputed["GPA"].mean())

# Replace missing majors with "Undeclared"
df_imputed["Major"] = df_imputed["Major"].fillna("Undeclared")

# Replace missing ages with the median age
df_imputed["Age"] = df_imputed["Age"].fillna(df["Age"].median())

df_imputed

             Major   Age   GPA
Name
James           AI  19.0  3.60
Chris           IT  20.0  3.32
Adam    Undeclared  18.5  2.90
Marian         CSC  18.0  3.32
Peter   Undeclared  18.5  3.10
Kevin   Undeclared  19.0  3.32
Linda           SW  18.5  3.32
Emma    Undeclared  20.0  3.80
Sophia          AI  18.0  3.32
Daniel         CSC  18.5  3.20