## Data Analytics

### Chapter 3: Data Manipulation (Filtering & Sorting)

Data manipulation is a fundamental step in data analysis, allowing you to transform and modify your dataset for more targeted insights. This chapter explores various techniques for manipulating data effectively.

- **Filtering**: Selecting a subset of your dataset based on certain criteria.

- **Sorting**: Arranging the rows of your dataset in a specific order based on one or more columns.

#### Generate Synthetic Data

In [45]:
import numpy as np
import pandas as pd

# Reproducible randomness
np.random.seed(42)

In [46]:
names = [
    "James", "Chris", "Adam", "Marian", "Peter",
    "Kevin", "Linda", "Emma", "Sophia", "Daniel",
    "Noah", "Olivia", "Lucas", "Grace", "Henry",
    "Liam", "Ava", "Mia", "Nathan", "Chloe"
]

majors = ["AI", "IT", "CSC", "SW"]

n = 20

df = pd.DataFrame({
    "Name": np.array(names),
    "Age": np.random.randint(18, 21, n),
    "Major": np.random.choice(majors, n),
    "GPA": np.round(np.random.uniform(2.0, 4.0, n), 2)
})

df

      Name  Age Major   GPA
0    James   20    SW  2.91
1    Chris   18    SW  3.57
2     Adam   20    AI  2.40
3   Marian   20    AI  3.03
4    Peter   18    SW  3.18
5    Kevin   18    IT  2.09
6    Linda   20    IT  3.22
7     Emma   19    AI  2.34
8   Sophia   20    SW  2.13
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
11  Olivia   20   CSC  3.62
12   Lucas   18   CSC  2.61
13   Grace   20   CSC  2.20
14   Henry   19    IT  3.37
15    Liam   18    SW  2.88
16     Ava   19    SW  2.24
17     Mia   19    SW  2.99
18  Nathan   19    SW  2.07
19   Chloe   19   CSC  3.82

#### 3.1. Boolean Series

Boolean Series is a series of True/False values that can be used to filter data in a DataFrame. It is often created by applying a condition to a column or multiple columns in the DataFrame.

In [47]:
# Return a Boolean series
df["GPA"] >= 3.5

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19     True
Name: GPA, dtype: bool

When combining the boolean series with the DataFrame, it returns a new DataFrame that only includes the rows where the condition is True.

In [48]:
# returns only the rows whose corresponding Boolean value is True
df[df["GPA"] >= 3.5]

      Name  Age Major   GPA
1    Chris   18    SW  3.57
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
11  Olivia   20   CSC  3.62
19   Chloe   19   CSC  3.82

#### 3.2. Filtering Based on Comparison Operators

Some common comparison operators used for filtering include:

- `==` (equal to)

- `!=` (not equal to)

- `>` (greater than)

- `<` (less than)

- `>=` (greater than or equal to)

- `<=` (less than or equal to)

In [49]:
# Example 1: Students with GPA greater than 3.5
df[df["GPA"] > 3.5]

      Name  Age Major   GPA
1    Chris   18    SW  3.57
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
11  Olivia   20   CSC  3.62
19   Chloe   19   CSC  3.82

In [50]:
# Example 2: Students aged 20
df[df["Age"] == 20]

      Name  Age Major   GPA
0    James   20    SW  2.91
2     Adam   20    AI  2.40
3   Marian   20    AI  3.03
6    Linda   20    IT  3.22
8   Sophia   20    SW  2.13
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
11  Olivia   20   CSC  3.62
13   Grace   20   CSC  2.20

In [51]:
# Example 3: Students who are not in the AI major
df[df["Major"] != "AI"]

      Name  Age Major   GPA
0    James   20    SW  2.91
1    Chris   18    SW  3.57
4    Peter   18    SW  3.18
5    Kevin   18    IT  2.09
6    Linda   20    IT  3.22
8   Sophia   20    SW  2.13
11  Olivia   20   CSC  3.62
12   Lucas   18   CSC  2.61
13   Grace   20   CSC  2.20
14   Henry   19    IT  3.37
15    Liam   18    SW  2.88
16     Ava   19    SW  2.24
17     Mia   19    SW  2.99
18  Nathan   19    SW  2.07
19   Chloe   19   CSC  3.82

#### 3.3. Filtering Based on Logical Conditions

Logical conditions can be combined using the following operators:

- `&` (and)

- `|` (or)

- `~` (not)

In [52]:
# Return students who are in the AI major and have a GPA greater than 3.5.
df[(df["Major"] == "AI") & (df["GPA"] > 3.5)]

      Name  Age Major   GPA
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93

In [53]:
# Return students who are either AI majors or have a GPA above 3.8.
df[(df["Major"] == "AI") | (df["GPA"] > 3.8)]

      Name  Age Major   GPA
2     Adam   20    AI  2.40
3   Marian   20    AI  3.03
7     Emma   19    AI  2.34
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
19   Chloe   19   CSC  3.82

In [54]:
# Return students who are not AI majors.
df[~(df["Major"] == "AI")]

      Name  Age Major   GPA
0    James   20    SW  2.91
1    Chris   18    SW  3.57
4    Peter   18    SW  3.18
5    Kevin   18    IT  2.09
6    Linda   20    IT  3.22
8   Sophia   20    SW  2.13
11  Olivia   20   CSC  3.62
12   Lucas   18   CSC  2.61
13   Grace   20   CSC  2.20
14   Henry   19    IT  3.37
15    Liam   18    SW  2.88
16     Ava   19    SW  2.24
17     Mia   19    SW  2.99
18  Nathan   19    SW  2.07
19   Chloe   19   CSC  3.82

#### 3.4. Filtering Based on Subset Membership

Three common methods for filtering based on subset membership include:

- Using the `isin()` method to filter rows based on whether a column's values are in a specified list.

- `any()` and `all()` methods to filter rows based on whether any or all of the specified conditions are met.

In [55]:
# Return students majoring in AI or CSC.
df[df["Major"].isin(["AI", "CSC"])]

      Name  Age Major   GPA
2     Adam   20    AI  2.40
3   Marian   20    AI  3.03
7     Emma   19    AI  2.34
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
11  Olivia   20   CSC  3.62
12   Lucas   18   CSC  2.61
13   Grace   20   CSC  2.20
19   Chloe   19   CSC  3.82

In [56]:
# Return True if at least one student has a GPA greater than 3.9.
(df["GPA"] > 3.9).any()

np.True_

In [57]:
# If every generated student is at least 18 years old, the result is True
(df["Age"] >= 18).all()

np.True_

#### 3.5. Filtering Based on String Conditions

String conditions can be used to filter rows based on text data. Some common string methods for filtering include:

- `str.contains()` to filter rows based on whether a column's values contain a specified substring.

- `str.startswith()` to filter rows based on whether a column's values start with a specified substring.

- `str.endswith()` to filter rows based on whether a column's values end with a specified substring.

In [58]:
# Names containing "an"
df[df["Name"].str.contains("an")]

      Name  Age Major   GPA
3   Marian   20    AI  3.03
9   Daniel   20    AI  3.90
18  Nathan   19    SW  2.07

In [59]:
# Example 2: Names starting with "A"
df[df["Name"].str.startswith("A")]

    Name  Age Major   GPA
2   Adam   20    AI  2.40
16   Ava   19    SW  2.24

In [60]:
# Example 3: Names ending with "a"
df[df["Name"].str.endswith("a")]

      Name  Age Major   GPA
6    Linda   20    IT  3.22
7     Emma   19    AI  2.34
8   Sophia   20    SW  2.13
11  Olivia   20   CSC  3.62
16     Ava   19    SW  2.24
17     Mia   19    SW  2.99

#### 3.6. Sorting by Column Values

When sorting a DataFrame by column values, you can specify one or more columns to sort by. The `sort_values()` method allows you to sort the DataFrame in ascending or descending order.

In [61]:
# Example 1: Sort by GPA
df.sort_values(by="GPA")

      Name  Age Major   GPA
18  Nathan   19    SW  2.07
5    Kevin   18    IT  2.09
8   Sophia   20    SW  2.13
13   Grace   20   CSC  2.20
16     Ava   19    SW  2.24
7     Emma   19    AI  2.34
2     Adam   20    AI  2.40
12   Lucas   18   CSC  2.61
15    Liam   18    SW  2.88
0    James   20    SW  2.91
17     Mia   19    SW  2.99
3   Marian   20    AI  3.03
4    Peter   18    SW  3.18
6    Linda   20    IT  3.22
14   Henry   19    IT  3.37
1    Chris   18    SW  3.57
11  Olivia   20   CSC  3.62
19   Chloe   19   CSC  3.82
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93

In [62]:
# Example 2: Sort in Descending Order
df.sort_values(by="GPA", ascending=False)

      Name  Age Major   GPA
10    Noah   20    AI  3.93
9   Daniel   20    AI  3.90
19   Chloe   19   CSC  3.82
11  Olivia   20   CSC  3.62
1    Chris   18    SW  3.57
14   Henry   19    IT  3.37
6    Linda   20    IT  3.22
4    Peter   18    SW  3.18
3   Marian   20    AI  3.03
17     Mia   19    SW  2.99
0    James   20    SW  2.91
15    Liam   18    SW  2.88
12   Lucas   18   CSC  2.61
2     Adam   20    AI  2.40
7     Emma   19    AI  2.34
16     Ava   19    SW  2.24
13   Grace   20   CSC  2.20
8   Sophia   20    SW  2.13
5    Kevin   18    IT  2.09
18  Nathan   19    SW  2.07

In [63]:
# Example 3: Sort by Multiple Columns
df.sort_values(by=["Major", "GPA"])

      Name  Age Major   GPA
7     Emma   19    AI  2.34
2     Adam   20    AI  2.40
3   Marian   20    AI  3.03
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
13   Grace   20   CSC  2.20
12   Lucas   18   CSC  2.61
11  Olivia   20   CSC  3.62
19   Chloe   19   CSC  3.82
5    Kevin   18    IT  2.09
6    Linda   20    IT  3.22
14   Henry   19    IT  3.37
18  Nathan   19    SW  2.07
8   Sophia   20    SW  2.13
16     Ava   19    SW  2.24
15    Liam   18    SW  2.88
0    James   20    SW  2.91
17     Mia   19    SW  2.99
4    Peter   18    SW  3.18
1    Chris   18    SW  3.57

In [64]:
# Each column can also have its own sorting direction.
df.sort_values(by=["Major", "GPA"], ascending=[True, False])

      Name  Age Major   GPA
10    Noah   20    AI  3.93
9   Daniel   20    AI  3.90
3   Marian   20    AI  3.03
2     Adam   20    AI  2.40
7     Emma   19    AI  2.34
19   Chloe   19   CSC  3.82
11  Olivia   20   CSC  3.62
12   Lucas   18   CSC  2.61
13   Grace   20   CSC  2.20
14   Henry   19    IT  3.37
6    Linda   20    IT  3.22
5    Kevin   18    IT  2.09
1    Chris   18    SW  3.57
4    Peter   18    SW  3.18
17     Mia   19    SW  2.99
0    James   20    SW  2.91
15    Liam   18    SW  2.88
16     Ava   19    SW  2.24
8   Sophia   20    SW  2.13
18  Nathan   19    SW  2.07

#### 3.7. Sorting by Index

Sorting by index requires the data to have meaningful index labels. The `sort_index()` method allows you to sort the DataFrame by its index in ascending or descending order.

In [65]:
df_index = df.set_index("Name")
df_index.sort_index()

        Age Major   GPA
Name
Adam     20    AI  2.40
Ava      19    SW  2.24
Chloe    19   CSC  3.82
Chris    18    SW  3.57
Daniel   20    AI  3.90
Emma     19    AI  2.34
Grace    20   CSC  2.20
Henry    19    IT  3.37
James    20    SW  2.91
Kevin    18    IT  2.09
Liam     18    SW  2.88
Linda    20    IT  3.22
Lucas    18   CSC  2.61
Marian   20    AI  3.03
Mia      19    SW  2.99
Nathan   19    SW  2.07
Noah     20    AI  3.93
Olivia   20   CSC  3.62
Peter    18    SW  3.18
Sophia   20    SW  2.13

#### 3.8. Duplicate Values in Sorting

Sorting can be improved by handling duplicate values. The `by` parameter in the `sort_values()` method allows you to specify multiple columns to sort by. 

When same values occur, immediately use the next column to sort by. This ensures that the sorting is stable and consistent.

In [66]:
df.sort_values(by=["Major", "Age", "GPA", "Name"])

      Name  Age Major   GPA
7     Emma   19    AI  2.34
2     Adam   20    AI  2.40
3   Marian   20    AI  3.03
9   Daniel   20    AI  3.90
10    Noah   20    AI  3.93
12   Lucas   18   CSC  2.61
19   Chloe   19   CSC  3.82
13   Grace   20   CSC  2.20
11  Olivia   20   CSC  3.62
5    Kevin   18    IT  2.09
14   Henry   19    IT  3.37
6    Linda   20    IT  3.22
15    Liam   18    SW  2.88
4    Peter   18    SW  3.18
1    Chris   18    SW  3.57
18  Nathan   19    SW  2.07
16     Ava   19    SW  2.24
17     Mia   19    SW  2.99
8   Sophia   20    SW  2.13
0    James   20    SW  2.91