## Data Analytics

### Chapter 8: Data Encoding (Feature Encoding)

Encoding is a technique used to convert categorical data into a numerical format that can be easily understood by machine learning algorithms. This process is essential for preparing data for modeling, as many algorithms require numerical input.

#### Generate Synthetic Data

In [21]:
import numpy as np
import pandas as pd

np.random.seed(42)

names = [
    "James", "Chris", "Adam", "Marian", "Peter",
    "Kevin", "Linda", "Emma", "Sophia", "Daniel",
    "Noah", "Olivia", "Lucas", "Grace", "Henry",
    "Liam", "Ava", "Mia", "Nathan", "Chloe"
]

n = len(names)

df = pd.DataFrame({
    "Name": names,
    "Age": np.random.randint(18, 21, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Major": np.random.choice(["AI", "IT", "CSC", "SW"], n),
    "English Level": np.random.choice(["A1", "A2", "B1", "B2"], n),
    "GPA": np.round(np.random.uniform(2.0, 4.0, n), 2)
})

df

      Name  Age  Gender Major English Level   GPA
0    James   20  Female    IT            B2  2.52
1    Chris   18  Female    IT            A2  3.33
2     Adam   20    Male   CSC            A2  2.62
3   Marian   20    Male    IT            A2  3.04
4    Peter   18  Female   CSC            A1  3.09
5    Kevin   18  Female    SW            A2  2.37
6    Linda   20  Female   CSC            A1  3.94
7     Emma   19    Male    SW            A2  3.55
8   Sophia   20  Female    SW            B2  3.88
9   Daniel   20    Male    AI            B2  3.79
10    Noah   20    Male   CSC            B1  3.20
11  Olivia   20    Male    AI            B2  3.84
12   Lucas   18    Male   CSC            B1  2.18
13   Grace   20    Male   CSC            B2  2.39
14   Henry   19  Female    AI            A1  2.09
15    Liam   18  Female    AI            B2  2.65
16     Ava   19  Female   CSC            B1  2.78
17     Mia   19  Female    IT            B1  2.54
18  Nathan   19  Female    SW            A2  3.66
19   Chloe   19    Male    AI            A1  2.71

#### 8.1. Label Encoding

Label Encoding is a method of converting categorical labels into numerical values. Each unique category is assigned a unique integer value. This technique is suitable for ordinal data, where the order of categories matters.

In [22]:
# label encoding can be implemented using map()
df_label_encoded = df.copy()

gender_map = {"Male": 0, "Female": 1}
df_label_encoded["Gender_Label"] = df_label_encoded["Gender"].map(gender_map)

df_label_encoded[["Gender", "Gender_Label"]]

    Gender  Gender_Label
0   Female             1
1   Female             1
2     Male             0
3     Male             0
4   Female             1
5   Female             1
6   Female             1
7     Male             0
8   Female             1
9     Male             0
10    Male             0
11    Male             0
12    Male             0
13    Male             0
14  Female             1
15  Female             1
16  Female             1
17  Female             1
18  Female             1
19    Male             0

In [23]:
major_map = {"AI": 0, "IT": 1, "CSC": 2, "SW": 3}
df_label_encoded["Major_Label"] = df_label_encoded["Major"].map(major_map)

# Remove the Gender and Major column
df_label_encoded = df_label_encoded.drop(columns=['Gender', 'Major'])

df_label_encoded

      Name  Age English Level   GPA  Gender_Label  Major_Label
0    James   20            B2  2.52             1            1
1    Chris   18            A2  3.33             1            1
2     Adam   20            A2  2.62             0            2
3   Marian   20            A2  3.04             0            1
4    Peter   18            A1  3.09             1            2
5    Kevin   18            A2  2.37             1            3
6    Linda   20            A1  3.94             1            2
7     Emma   19            A2  3.55             0            3
8   Sophia   20            B2  3.88             1            3
9   Daniel   20            B2  3.79             0            0
10    Noah   20            B1  3.20             0            2
11  Olivia   20            B2  3.84             0            0
12   Lucas   18            B1  2.18             0            2
13   Grace   20            B2  2.39             0            2
14   Henry   19            A1  2.09             1            0
15    Liam   18            B2  2.65             1            0
16     Ava   19            B1  2.78             1            2
17     Mia   19            B1  2.54             1            1
18  Nathan   19            A2  3.66             1            3
19   Chloe   19            A1  2.71             0            0

#### 8.2. One-Hot Encoding

One-Hot Encoding is a technique that converts categorical variables into a binary matrix representation. Each category is represented by a binary vector, where only one element is "hot" (1) and the rest are "cold" (0). This method is suitable for nominal data, where the order of categories does not matter.

One-Hot Vector is a representation of categorical variables as binary vectors, where each category is represented by a unique vector with a single "hot" (1) element and the rest as "cold" (0) elements.

In [24]:
major_onehot = pd.get_dummies(df["Major"], 
                              prefix="Major")
major_onehot

    Major_AI  Major_CSC  Major_IT  Major_SW
0      False      False      True     False
1      False      False      True     False
2      False       True     False     False
3      False      False      True     False
4      False       True     False     False
5      False      False     False      True
6      False       True     False     False
7      False      False     False      True
8      False      False     False      True
9       True      False     False     False
10     False       True     False     False
11      True      False     False     False
12     False       True     False     False
13     False       True     False     False
14      True      False     False     False
15      True      False     False     False
16     False       True     False     False
17     False      False      True     False
18     False      False     False      True
19      True      False     False     False

In [25]:
# This also automatically drops the "Gender" and "Major" columns
df_onehot = pd.get_dummies(df, columns=["Gender", "Major"])
df_onehot

,Name,Age,English Level,GPA,Gender_Female,Gender_Male,Major_AI,Major_CSC,Major_IT,Major_SW
0,James,20,B2,2.52,True,False,False,False,True,False
1,Chris,18,A2,3.33,True,False,False,False,True,False
2,Adam,20,A2,2.62,False,True,False,True,False,False
3,Marian,20,A2,3.04,False,True,False,False,True,False
4,Peter,18,A1,3.09,True,False,False,True,False,False
5,Kevin,18,A2,2.37,True,False,False,False,False,True
6,Linda,20,A1,3.94,True,False,False,True,False,False
7,Emma,19,A2,3.55,False,True,False,False,False,True
8,Sophia,20,B2,3.88,True,False,False,False,False,True
9,Daniel,20,B2,3.79,False,True,True,False,False,False
10,Noah,20,B1,3.20,False,True,False,True,False,False
11,Olivia,20,B2,3.84,False,True,True,False,False,False
12,Lucas,18,B1,2.18,False,True,False,True,False,False
13,Grace,20,B2,2.39,False,True,False,True,False,False
14,Henry,19,A1,2.09,True,False,True,False,False,False
15,Liam,18,B2,2.65,True,False,True,False,False,False
16,Ava,19,B1,2.78,True,False,False,True,False,False
17,Mia,19,B1,2.54,True,False,False,False,True,False
18,Nathan,19,A2,3.66,True,False,False,False,False,True
19,Chloe,19,A1,2.71,False,True,True,False,False,False

In [ ]:
# We can replace the True/False with 0/1 using replace(), 
# which is very important for model training
df_onehot = df_onehot.replace({True: 1, False: 0})
df_onehot

/var/folders/gc/49grx5f90nv3f12yh4jhhf740000gn/T/ipykernel_41960/2657741063.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_onehot = df_onehot.replace({True: 1, False: 0})

,Name,Age,English Level,GPA,Gender_Female,Gender_Male,Major_AI,Major_CSC,Major_IT,Major_SW
0,James,20,B2,2.52,1,0,0,0,1,0
1,Chris,18,A2,3.33,1,0,0,0,1,0
2,Adam,20,A2,2.62,0,1,0,1,0,0
3,Marian,20,A2,3.04,0,1,0,0,1,0
4,Peter,18,A1,3.09,1,0,0,1,0,0
5,Kevin,18,A2,2.37,1,0,0,0,0,1
6,Linda,20,A1,3.94,1,0,0,1,0,0
7,Emma,19,A2,3.55,0,1,0,0,0,1
8,Sophia,20,B2,3.88,1,0,0,0,0,1
9,Daniel,20,B2,3.79,0,1,1,0,0,0
10,Noah,20,B1,3.20,0,1,0,1,0,0
11,Olivia,20,B2,3.84,0,1,1,0,0,0
12,Lucas,18,B1,2.18,0,1,0,1,0,0
13,Grace,20,B2,2.39,0,1,0,1,0,0
14,Henry,19,A1,2.09,1,0,1,0,0,0
15,Liam,18,B2,2.65,1,0,1,0,0,0
16,Ava,19,B1,2.78,1,0,0,1,0,0
17,Mia,19,B1,2.54,1,0,0,0,1,0
18,Nathan,19,A2,3.66,1,0,0,0,0,1
19,Chloe,19,A1,2.71,0,1,1,0,0,0

#### 8.3. Ordinal Encoding

Ordinal Encoding is a technique used to convert categorical variables with a meaningful order into numerical values. Each category is assigned an integer value based on its order or rank. This method is suitable for ordinal data, where the order of categories matters.

In [27]:
df_ordinal_encoded = df.copy()

english_map = {"A1": 1, "A2": 2, "B1": 3, "B2": 4}
df_ordinal_encoded["English_Ordinal"] = df_ordinal_encoded["English Level"].map(english_map)

# Remove the English Level column
df_ordinal_encoded = df_ordinal_encoded.drop(columns=["English Level"])

df_ordinal_encoded

      Name  Age  Gender Major   GPA  English_Ordinal
0    James   20  Female    IT  2.52                4
1    Chris   18  Female    IT  3.33                2
2     Adam   20    Male   CSC  2.62                2
3   Marian   20    Male    IT  3.04                2
4    Peter   18  Female   CSC  3.09                1
5    Kevin   18  Female    SW  2.37                2
6    Linda   20  Female   CSC  3.94                1
7     Emma   19    Male    SW  3.55                2
8   Sophia   20  Female    SW  3.88                4
9   Daniel   20    Male    AI  3.79                4
10    Noah   20    Male   CSC  3.20                3
11  Olivia   20    Male    AI  3.84                4
12   Lucas   18    Male   CSC  2.18                3
13   Grace   20    Male   CSC  2.39                4
14   Henry   19  Female    AI  2.09                1
15    Liam   18  Female    AI  2.65                4
16     Ava   19  Female   CSC  2.78                3
17     Mia   19  Female    IT  2.54                3
18  Nathan   19  Female    SW  3.66                2
19   Chloe   19    Male    AI  2.71                1