## Data Analytics

### Chapter 14: Exploratory Data Analysis - Part II

#### Generate Synthetic Data

In [10]:
import numpy as np
import pandas as pd

np.random.seed(42)

In [11]:
n = 20

names = [
    "James", "Chris", "Adam", "Marian", "Peter",
    "Kevin", "Linda", "Emma", "Sophia", "Daniel",
    "Noah", "Olivia", "Lucas", "Grace", "Henry",
    "Liam", "Ava", "Mia", "Nathan", "Chloe"
]

df = pd.DataFrame({
    "Name": names,
    "Age": np.random.randint(18, 22, n),
    "Major": np.random.choice(["AI", "CSC", "IT", "SW"], n),
    "GPA": np.round(np.random.uniform(2.0, 4.0, n), 2)
})

df

      Name  Age Major   GPA
0    James   20   CSC  3.22
1    Chris   21    AI  2.28
2     Adam   18   CSC  2.58
3   Marian   20    SW  2.73
4    Peter   20    SW  2.91
5    Kevin   21   CSC  3.57
6    Linda   18   CSC  2.40
7     Emma   18   CSC  3.03
8   Sophia   20    SW  3.18
9   Daniel   19    SW  2.09
10    Noah   20    AI  3.22
11  Olivia   20    AI  2.34
12   Lucas   20    SW  2.13
13   Grace   20   CSC  3.90
14   Henry   21   CSC  3.93
15    Liam   18    AI  3.62
16     Ava   21    SW  2.61
17     Mia   21    AI  2.20
18  Nathan   21    AI  3.37
19   Chloe   20    IT  2.88

#### **14.1. Mean, Median, and Mode**

- **Mean:** The arithmetic average of all values.
- **Median:** The middle value after sorting the data.
- **Mode:** The value that appears most frequently.

Pandas provides built-in methods to compute each statistic.

In [12]:
print("Mean GPA:", df["GPA"].mean())
print("Median GPA:", df["GPA"].median())
print("Mode GPA:")
print(df["GPA"].mode())

Mean GPA: 2.9095000000000004
Median GPA: 2.895
Mode GPA:
0    3.22
Name: GPA, dtype: float64

#### **14.2. Quartiles**

Quartiles divide a sorted dataset into four equal parts.

- **Q1 (Lower Quartile):** The median of the lower half of the data.
- **Q2 (Median):** The median of the entire dataset.
- **Q3 (Upper Quartile):** The median of the upper half of the data.

These values are commonly used to understand the spread of data and are essential for box plots and outlier detection.

In [13]:
print("Q1:", df["GPA"].quantile(0.25))
print("Q2:", df["GPA"].quantile(0.50))
print("Q3:", df["GPA"].quantile(0.75))

Q1: 2.385
Q2: 2.895
Q3: 3.2575000000000003

#### **14.3. Variance and Standard Deviation**

While measures of central tendency describe the center of the data, **variance** and **standard deviation** describe how spread out the values are.

In [14]:
print("Variance:", df["GPA"].var())
print("Standard Deviation:", df["GPA"].std())

Variance: 0.3394892105263158
Standard Deviation: 0.5826570264969915

#### **14.4. Lambda Function**

Lambda functions provide a convenient way to apply simple operations to every value in a Series without defining a separate function.

In [15]:
# we can convert GPA scores to percentages.
df["GPA (%)"] = df["GPA"].map(lambda x: round(x / 4 * 100, 1))

df

      Name  Age Major   GPA  GPA (%)
0    James   20   CSC  3.22     80.5
1    Chris   21    AI  2.28     57.0
2     Adam   18   CSC  2.58     64.5
3   Marian   20    SW  2.73     68.2
4    Peter   20    SW  2.91     72.8
5    Kevin   21   CSC  3.57     89.2
6    Linda   18   CSC  2.40     60.0
7     Emma   18   CSC  3.03     75.8
8   Sophia   20    SW  3.18     79.5
9   Daniel   19    SW  2.09     52.2
10    Noah   20    AI  3.22     80.5
11  Olivia   20    AI  2.34     58.5
12   Lucas   20    SW  2.13     53.2
13   Grace   20   CSC  3.90     97.5
14   Henry   21   CSC  3.93     98.2
15    Liam   18    AI  3.62     90.5
16     Ava   21    SW  2.61     65.2
17     Mia   21    AI  2.20     55.0
18  Nathan   21    AI  3.37     84.2
19   Chloe   20    IT  2.88     72.0

In [16]:
# We can also classify students according to their GPA.
df["Performance"] = df["GPA"].map(
    lambda x: "Excellent" if x >= 3.5
    else "Good" if x >= 3.0
    else "Average"
)

df

      Name  Age Major   GPA  GPA (%) Performance
0    James   20   CSC  3.22     80.5        Good
1    Chris   21    AI  2.28     57.0     Average
2     Adam   18   CSC  2.58     64.5     Average
3   Marian   20    SW  2.73     68.2     Average
4    Peter   20    SW  2.91     72.8     Average
5    Kevin   21   CSC  3.57     89.2   Excellent
6    Linda   18   CSC  2.40     60.0     Average
7     Emma   18   CSC  3.03     75.8        Good
8   Sophia   20    SW  3.18     79.5        Good
9   Daniel   19    SW  2.09     52.2     Average
10    Noah   20    AI  3.22     80.5        Good
11  Olivia   20    AI  2.34     58.5     Average
12   Lucas   20    SW  2.13     53.2     Average
13   Grace   20   CSC  3.90     97.5   Excellent
14   Henry   21   CSC  3.93     98.2   Excellent
15    Liam   18    AI  3.62     90.5   Excellent
16     Ava   21    SW  2.61     65.2     Average
17     Mia   21    AI  2.20     55.0     Average
18  Nathan   21    AI  3.37     84.2        Good
19   Chloe   20    IT  2.88     72.0     Average

#### **14.5. Using a User-Defined Function with `map()`**

While lambda functions are convenient for simple operations, defining a regular function is often more readable when the logic becomes more complex or when the function will be reused. The function can then be passed directly to `map()`.

In [17]:
def get_grade(gpa):
    if gpa >= 3.7:
        return "A"
    elif gpa >= 3.3:
        return "B+"
    elif gpa >= 3.0:
        return "B"
    elif gpa >= 2.5:
        return "C"
    else:
        return "D"

df["Letter Grade"] = df["GPA"].map(get_grade)

df[["Name", "GPA", "Letter Grade"]]

      Name   GPA Letter Grade
0    James  3.22            B
1    Chris  2.28            D
2     Adam  2.58            C
3   Marian  2.73            C
4    Peter  2.91            C
5    Kevin  3.57           B+
6    Linda  2.40            D
7     Emma  3.03            B
8   Sophia  3.18            B
9   Daniel  2.09            D
10    Noah  3.22            B
11  Olivia  2.34            D
12   Lucas  2.13            D
13   Grace  3.90            A
14   Henry  3.93            A
15    Liam  3.62           B+
16     Ava  2.61            C
17     Mia  2.20            D
18  Nathan  3.37           B+
19   Chloe  2.88            C

In [18]:
df["GPA2"] = np.round(np.random.uniform(2.0, 4.0, len(df)), 2)
df["Letter Grade 2"] = df["GPA2"].map(get_grade)

df[["GPA", "GPA2", "Letter Grade", "Letter Grade 2"]]

     GPA  GPA2 Letter Grade Letter Grade 2
0   3.22  2.24            B              D
1   2.28  2.99            D              C
2   2.58  2.07            C              D
3   2.73  3.82            C              A
4   2.91  2.52            C              C
5   3.57  3.33           B+             B+
6   2.40  2.62            D              C
7   3.03  3.04            B              B
8   3.18  3.09            B              B
9   2.09  2.37            D              D
10  3.22  3.94            B              A
11  2.34  3.55            D             B+
12  2.13  3.88            D              A
13  3.90  3.79            A              A
14  3.93  3.20            A              B
15  3.62  3.84           B+              A
16  2.61  2.18            C              D
17  2.20  2.39            D              D
18  3.37  2.09           B+              D
19  2.88  2.65            C              C