## Data Analytics

### Chapter 10: Data Combination (Concatenation, Comparison, and Segmentation)

- Concatenating DataFrames combines multiple DataFrames by stacking them vertically (adding rows) or horizontally (adding columns). Pandas provides the `pd.concat()` function to combine multiple DataFrames.

- Comparing DataFrames identifies the differences between two similar DataFrames, making it useful for validating updates or detecting changes after data preprocessing.

- Segmentation groups continuous numerical values into categorical intervals using pd.cut(), allowing numerical features to be represented as meaningful categories for analysis or machine learning.

#### Generate Synthetic Data

In [17]:
import numpy as np
import pandas as pd

np.random.seed(42)

In [18]:
studentAI = pd.DataFrame({
    "Name": [f"AI_{i}" for i in range(1,21)],
    "Age": np.random.randint(18,22,20),
    "GPA": np.round(np.random.uniform(2.0,4.0,20),2)
})


studentAI

     Name  Age   GPA
0    AI_1   20  2.04
1    AI_2   21  3.94
2    AI_3   18  3.66
3    AI_4   20  2.42
4    AI_5   20  2.36
5    AI_6   21  2.37
6    AI_7   18  2.61
7    AI_8   18  3.05
8    AI_9   20  2.86
9   AI_10   19  2.58
10  AI_11   20  3.22
11  AI_12   20  2.28
12  AI_13   20  2.58
13  AI_14   20  2.73
14  AI_15   21  2.91
15  AI_16   18  3.57
16  AI_17   21  2.40
17  AI_18   21  3.03
18  AI_19   21  3.18
19  AI_20   20  2.09

In [19]:
studentCSC = pd.DataFrame({
    "Name": [f"CSC_{i}" for i in range(1,21)],
    "Age": np.random.randint(18,22,20),
    "GPA": np.round(np.random.uniform(2.0,4.0,20),2)
})

studentCSC

      Name  Age   GPA
0    CSC_1   20  2.24
1    CSC_2   20  2.99
2    CSC_3   18  2.07
3    CSC_4   18  3.82
4    CSC_5   20  2.52
5    CSC_6   19  3.33
6    CSC_7   21  2.62
7    CSC_8   18  3.04
8    CSC_9   21  3.09
9   CSC_10   19  2.37
10  CSC_11   19  3.94
11  CSC_12   19  3.55
12  CSC_13   18  3.88
13  CSC_14   19  3.79
14  CSC_15   18  3.20
15  CSC_16   19  3.84
16  CSC_17   21  2.18
17  CSC_18   21  2.39
18  CSC_19   20  2.09
19  CSC_20   21  2.65

#### 10.1. Vertical Concatenation

Row-wise (Vertical): Stack one dataset below another. This is commonly used when combining datasets with identical columns.

In [20]:
result = pd.concat(
    [studentAI, studentCSC],
    axis=0,
    ignore_index=True
)

result

      Name  Age   GPA
0     AI_1   20  2.04
1     AI_2   21  3.94
2     AI_3   18  3.66
3     AI_4   20  2.42
4     AI_5   20  2.36
5     AI_6   21  2.37
6     AI_7   18  2.61
7     AI_8   18  3.05
8     AI_9   20  2.86
9    AI_10   19  2.58
10   AI_11   20  3.22
11   AI_12   20  2.28
12   AI_13   20  2.58
13   AI_14   20  2.73
14   AI_15   21  2.91
15   AI_16   18  3.57
16   AI_17   21  2.40
17   AI_18   21  3.03
18   AI_19   21  3.18
19   AI_20   20  2.09
20   CSC_1   20  2.24
21   CSC_2   20  2.99
22   CSC_3   18  2.07
23   CSC_4   18  3.82
24   CSC_5   20  2.52
25   CSC_6   19  3.33
26   CSC_7   21  2.62
27   CSC_8   18  3.04
28   CSC_9   21  3.09
29  CSC_10   19  2.37
30  CSC_11   19  3.94
31  CSC_12   19  3.55
32  CSC_13   18  3.88
33  CSC_14   19  3.79
34  CSC_15   18  3.20
35  CSC_16   19  3.84
36  CSC_17   21  2.18
37  CSC_18   21  2.39
38  CSC_19   20  2.09
39  CSC_20   21  2.65

#### 10.2. Horizontal Concatenation

Column-wise (Horizontal): Place datasets side-by-side. Unlike merge(), the DataFrames do not need a common key, but they should have the same number of rows or compatible indexes.

In [21]:
result = pd.concat(
    [studentAI, studentCSC],
    axis=1
)

result

     Name  Age   GPA    Name  Age   GPA
0    AI_1   20  2.04   CSC_1   20  2.24
1    AI_2   21  3.94   CSC_2   20  2.99
2    AI_3   18  3.66   CSC_3   18  2.07
3    AI_4   20  2.42   CSC_4   18  3.82
4    AI_5   20  2.36   CSC_5   20  2.52
5    AI_6   21  2.37   CSC_6   19  3.33
6    AI_7   18  2.61   CSC_7   21  2.62
7    AI_8   18  3.05   CSC_8   18  3.04
8    AI_9   20  2.86   CSC_9   21  3.09
9   AI_10   19  2.58  CSC_10   19  2.37
10  AI_11   20  3.22  CSC_11   19  3.94
11  AI_12   20  2.28  CSC_12   19  3.55
12  AI_13   20  2.58  CSC_13   18  3.88
13  AI_14   20  2.73  CSC_14   19  3.79
14  AI_15   21  2.91  CSC_15   18  3.20
15  AI_16   18  3.57  CSC_16   19  3.84
16  AI_17   21  2.40  CSC_17   21  2.18
17  AI_18   21  3.03  CSC_18   21  2.39
18  AI_19   21  3.18  CSC_19   20  2.09
19  AI_20   20  2.09  CSC_20   21  2.65

#### 10.3. Comparing Two DataFrames

During data cleaning or preprocessing, it is common to compare two similar DataFrames to determine which values have changed. Pandas provides the `compare()` method to highlight these differences.

In [22]:
studentAI2 = studentAI.copy()

studentAI2.loc[0, "GPA"] = 3.95
studentAI2.loc[3, "Age"] = 21
studentAI2.loc[5, "GPA"] = 2.50

comparison = studentAI.compare(studentAI2)

comparison

    Age         GPA
   self other  self other
0   NaN   NaN  2.04  3.95
3  20.0  21.0   NaN   NaN
5   NaN   NaN  2.37  2.50

#### 10.4. Data Segmentation

Sometimes it is useful to convert continuous numerical values into categorical groups. This process is known as **segmentation** or **binning**.

Pandas provides the **`pd.cut()`** function to divide numerical values into intervals.

In [23]:
# Segmenting Age
studentAI["Age Group"] = pd.cut(
    studentAI["Age"],
    bins=[17,18,20,22],
    labels=["18","19-20","21"]
)

studentAI

     Name  Age   GPA Age Group
0    AI_1   20  2.04     19-20
1    AI_2   21  3.94        21
2    AI_3   18  3.66        18
3    AI_4   20  2.42     19-20
4    AI_5   20  2.36     19-20
5    AI_6   21  2.37        21
6    AI_7   18  2.61        18
7    AI_8   18  3.05        18
8    AI_9   20  2.86     19-20
9   AI_10   19  2.58     19-20
10  AI_11   20  3.22     19-20
11  AI_12   20  2.28     19-20
12  AI_13   20  2.58     19-20
13  AI_14   20  2.73     19-20
14  AI_15   21  2.91        21
15  AI_16   18  3.57        18
16  AI_17   21  2.40        21
17  AI_18   21  3.03        21
18  AI_19   21  3.18        21
19  AI_20   20  2.09     19-20

In [24]:
# Segmenting GPA
studentAI["Performance"] = pd.cut(
    studentAI["GPA"],
    bins=[0,2.5,3.2,4.0],
    labels=["Low","Average","High"]
)

studentAI

     Name  Age   GPA Age Group Performance
0    AI_1   20  2.04     19-20         Low
1    AI_2   21  3.94        21        High
2    AI_3   18  3.66        18        High
3    AI_4   20  2.42     19-20         Low
4    AI_5   20  2.36     19-20         Low
5    AI_6   21  2.37        21         Low
6    AI_7   18  2.61        18     Average
7    AI_8   18  3.05        18     Average
8    AI_9   20  2.86     19-20     Average
9   AI_10   19  2.58     19-20     Average
10  AI_11   20  3.22     19-20        High
11  AI_12   20  2.28     19-20         Low
12  AI_13   20  2.58     19-20     Average
13  AI_14   20  2.73     19-20     Average
14  AI_15   21  2.91        21     Average
15  AI_16   18  3.57        18        High
16  AI_17   21  2.40        21         Low
17  AI_18   21  3.03        21     Average
18  AI_19   21  3.18        21     Average
19  AI_20   20  2.09     19-20         Low