## Data Analytics

### Chapter 13: Exploratory Data Analysis - Part I

Exploratory Data Analysis (EDA) is the process of investigating and summarizing data using statistical methods and visualizations. 

The objective is to understand the underlying structure of the data, discover patterns, identify unusual observations, and explore relationships between variables before performing more advanced analysis.

#### Generate Synthetic Data

In [51]:
import numpy as np
import pandas as pd

np.random.seed(42)

In [52]:
n = 20

names = [
    "James", "Chris", "Adam", "Marian", "Peter",
    "Kevin", "Linda", "Emma", "Sophia", "Daniel",
    "Noah", "Olivia", "Lucas", "Grace", "Henry",
    "Liam", "Ava", "Mia", "Nathan", "Chloe"
]

df = pd.DataFrame({
    "Name": names,
    "Age": np.random.randint(18, 22, n),
    "Major": np.random.choice(["AI", "CSC", "IT", "SW"], n),
    "GPA": np.round(np.random.uniform(2.0, 4.0, n), 2)
})

df

      Name  Age Major   GPA
0    James   20   CSC  3.22
1    Chris   21    AI  2.28
2     Adam   18   CSC  2.58
3   Marian   20    SW  2.73
4    Peter   20    SW  2.91
5    Kevin   21   CSC  3.57
6    Linda   18   CSC  2.40
7     Emma   18   CSC  3.03
8   Sophia   20    SW  3.18
9   Daniel   19    SW  2.09
10    Noah   20    AI  3.22
11  Olivia   20    AI  2.34
12   Lucas   20    SW  2.13
13   Grace   20   CSC  3.90
14   Henry   21   CSC  3.93
15    Liam   18    AI  3.62
16     Ava   21    SW  2.61
17     Mia   21    AI  2.20
18  Nathan   21    AI  3.37
19   Chloe   20    IT  2.88

#### Retrieve Basic Information

- **`df.info()`** displays the dataset structure, including the number of rows, columns, data types, and missing values.
- **`df.describe()`** summarizes numerical columns by reporting statistics such as count, mean, standard deviation, minimum, quartiles, and maximum.

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    20 non-null     object
 1   Age     20 non-null     int64
 2   Major   20 non-null     object
 3   GPA     20 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 772.0+ bytes

In [54]:
df.describe()

             Age        GPA
count  20.000000  20.000000
mean   19.850000   2.909500
std     1.089423   0.582657
min    18.000000   2.090000
25%    19.750000   2.385000
50%    20.000000   2.895000
75%    21.000000   3.257500
max    21.000000   3.930000

In [55]:
df.describe(include='all')

         Name        Age Major        GPA
count      20  20.000000    20  20.000000
unique     20        NaN     4        NaN
top     James        NaN   CSC        NaN
freq        1        NaN     7        NaN
mean      NaN  19.850000   NaN   2.909500
std       NaN   1.089423   NaN   0.582657
min       NaN  18.000000   NaN   2.090000
25%       NaN  19.750000   NaN   2.385000
50%       NaN  20.000000   NaN   2.895000
75%       NaN  21.000000   NaN   3.257500
max       NaN  21.000000   NaN   3.930000

In [56]:
# create a second GPA column that will be used 
# to demonstrate arithmetic operations.
df_temp = df.copy()

df_temp["GPA2"] = np.round(np.random.uniform(2.0, 4.0, len(df)), 2)
df_temp[["Name", "GPA", "GPA2"]]

      Name   GPA  GPA2
0    James  3.22  2.24
1    Chris  2.28  2.99
2     Adam  2.58  2.07
3   Marian  2.73  3.82
4    Peter  2.91  2.52
5    Kevin  3.57  3.33
6    Linda  2.40  2.62
7     Emma  3.03  3.04
8   Sophia  3.18  3.09
9   Daniel  2.09  2.37
10    Noah  3.22  3.94
11  Olivia  2.34  3.55
12   Lucas  2.13  3.88
13   Grace  3.90  3.79
14   Henry  3.93  3.20
15    Liam  3.62  3.84
16     Ava  2.61  2.18
17     Mia  2.20  2.39
18  Nathan  3.37  2.09
19   Chloe  2.88  2.65

#### 13.1. Basic Statistical Operations

Pandas provide several functions allow us to perform arithmetic on columns, summarize numerical data, and identify the largest or smallest values.

- **Arithmetic Operations**: Pandas supports element-wise arithmetic between columns.

In [57]:
# Addition
df_temp["GPA_Add"] = df_temp["GPA"].add(df_temp["GPA2"])

# Subtraction
df_temp["GPA_Sub"] = df_temp["GPA"].sub(df_temp["GPA2"])

# Multiplication
df_temp["GPA_Mul"] = df_temp["GPA"].multiply(df_temp["GPA2"])

# Division
df_temp["GPA_Div"] = df_temp["GPA"].divide(df_temp["GPA2"])

df_temp[["GPA", "GPA2", "GPA_Add", "GPA_Sub", "GPA_Mul", "GPA_Div"]]

     GPA  GPA2  GPA_Add  GPA_Sub  GPA_Mul   GPA_Div
0   3.22  2.24     5.46     0.98   7.2128  1.437500
1   2.28  2.99     5.27    -0.71   6.8172  0.762542
2   2.58  2.07     4.65     0.51   5.3406  1.246377
3   2.73  3.82     6.55    -1.09  10.4286  0.714660
4   2.91  2.52     5.43     0.39   7.3332  1.154762
5   3.57  3.33     6.90     0.24  11.8881  1.072072
6   2.40  2.62     5.02    -0.22   6.2880  0.916031
7   3.03  3.04     6.07    -0.01   9.2112  0.996711
8   3.18  3.09     6.27     0.09   9.8262  1.029126
9   2.09  2.37     4.46    -0.28   4.9533  0.881857
10  3.22  3.94     7.16    -0.72  12.6868  0.817259
11  2.34  3.55     5.89    -1.21   8.3070  0.659155
12  2.13  3.88     6.01    -1.75   8.2644  0.548969
13  3.90  3.79     7.69     0.11  14.7810  1.029024
14  3.93  3.20     7.13     0.73  12.5760  1.228125
15  3.62  3.84     7.46    -0.22  13.9008  0.942708
16  2.61  2.18     4.79     0.43   5.6898  1.197248
17  2.20  2.39     4.59    -0.19   5.2580  0.920502
18  3.37  2.09     5.46     1.28   7.0433  1.612440
19  2.88  2.65     5.53     0.23   7.6320  1.086792

- **Maximum and Minimum**: The maximum and minimum values can be obtained using `max()` and `min()`.

In [58]:
print("Maximum GPA:", df["GPA"].max())
print("Minimum GPA:", df["GPA"].min())

Maximum GPA: 3.93
Minimum GPA: 2.09

- **Largest and Smallest Values**: To retrieve the largest or smallest observations, use `nlargest()` and `nsmallest()`.

In [59]:
# Top 5 highest GPAs
df.nlargest(5, "GPA")

      Name  Age Major   GPA
14   Henry   21   CSC  3.93
13   Grace   20   CSC  3.90
15    Liam   18    AI  3.62
5    Kevin   21   CSC  3.57
18  Nathan   21    AI  3.37

In [60]:
# Bottom 5 lowest GPAs
df.nsmallest(5, "GPA")

      Name  Age Major   GPA
9   Daniel   19    SW  2.09
12   Lucas   20    SW  2.13
17     Mia   21    AI  2.20
1    Chris   21    AI  2.28
11  Olivia   20    AI  2.34

- **Counting Values**: The `count()` function counts the number of non-missing values in each column.

In [61]:
df.count()

Name     20
Age      20
Major    20
GPA      20
dtype: int64

- To count the occurrences of each unique value, use `value_counts()`.

In [62]:
df["Major"].value_counts()

Major
CSC    7
AI     6
SW     6
IT     1
Name: count, dtype: int64

In [63]:
# The same method can also be applied to numerical columns.
df["Age"].value_counts()

Age
20    9
21    6
18    4
19    1
Name: count, dtype: int64

- **Summation**: The `sum()` function computes the total of a numerical column.

In [64]:
print("Total GPA:", df["GPA"].sum())

Total GPA: 58.190000000000005

In [65]:
# It can also be applied to multiple numerical columns
# using df.temp()
df_temp[["GPA", "GPA2"]].sum()

GPA     58.19
GPA2    59.60
dtype: float64